In [0]:
%pip install openpyxl

Requirement already satisfied: openpyxl in /local_disk0/.ephemeral_nfs/envs/pythonEnv-22c8cfcc-84cb-4628-86dc-62ce36cc3548/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /local_disk0/.ephemeral_nfs/envs/pythonEnv-22c8cfcc-84cb-4628-86dc-62ce36cc3548/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
dbutils.library.restartPython()

In [0]:
from pyspark.sql import functions as F
from pyspark.sql.functions import regexp_extract

dataset_judicial = spark.read.format("delta").load(
    "/Volumes/workspace/default/tfm_visnu_raw/dataset_judicial_inicial_delta"
)

display(dataset_judicial)

In [0]:
dataset_con_ciudad = dataset_judicial.withColumn(
    "ciudad",
    regexp_extract("orgjud", r"NR\.\s*\d+\s+(.*)", 1)
)

display(dataset_con_ciudad)

In [0]:
dataset_con_ciudad_norm = (
    dataset_con_ciudad
    .withColumn("ciudad", F.upper(F.trim(F.col("ciudad"))))
    .withColumn("ciudad", F.regexp_replace("ciudad", r"\s+", " "))
)

In [0]:
mapping_final = [
    ("A CORUÑA", "A CORUÑA"),
    ("A ESTRADA", "PONTEVEDRA"),
    ("AGUILAR", "CORDOBA"),
    ("ALBACETE", "ALBACETE"),
    ("ALCALA DE GUADAIRA", "SEVILLA"),
    ("ALCALA DE HENARES", "MADRID"),
    ("ALCALA LA REAL", "JAEN"),
    ("ALCARAZ", "ALBACETE"),
    ("ALCAZAR DE SAN JUAN", "CIUDAD REAL"),
    ("ALCAÑIZ", "TERUEL"),
    ("ALCOBENDAS", "MADRID"),
    ("ALCORCON", "MADRID"),
    ("ALCOY", "ALICANTE"),
    ("ALGECIRAS", "CADIZ"),
    ("ALICANTE/ALACANT", "ALICANTE"),
    ("ALMADEN", "CIUDAD REAL"),
    ("ALMAGRO", "CIUDAD REAL"),
    ("ALMANSA", "ALBACETE"),
    ("ALMAZAN", "SORIA"),
    ("ALMENDRALEJO", "BADAJOZ"),
    ("ALMERIA", "ALMERIA"),
    ("ANTEQUERA", "MALAGA"),
    ("ARACENA", "HUELVA"),
    ("ARANDA DE DUERO", "BURGOS"),
    ("ARCOS DE LA FRONTERA", "CADIZ"),
    ("BADALONA", "BARCELONA"),
    ("BAZA", "GRANADA"),
    ("BERJA", "ALMERIA"),
    ("COLLADO VILLALBA", "MADRID"),
    ("CORCUBION", "A CORUÑA"),
    ("CUENCA", "CUENCA"),
    ("DURANGO", "BIZKAIA"),
    ("FONSAGRADA", "LUGO"),
    ("FREGENAL DE LA SIERRA", "BADAJOZ"),
    ("GETAFE", "MADRID"),
    ("GUADIX", "GRANADA"),
    ("HUESCAR", "GRANADA"),
    ("JACA", "HUESCA"),
    ("JEREZ DE LA FRONTERA", "CADIZ"),
    ("LAREDO", "CANTABRIA"),
    ("LEGANES", "MADRID"),
    ("LORCA", "MURCIA"),
    ("MADRID", "MADRID"),
    ("MALAGA", "MALAGA"),
    ("MEDINA DEL CAMPO", "VALLADOLID"),
    ("MERIDA", "BADAJOZ"),
    ("MOTILLA DEL PALANCAR", "CUENCA"),
    ("MURCIA", "MURCIA"),
    ("NAVALMORAL DE LA MATA", "CACERES"),
    ("NEGREIRA", "A CORUÑA"),
    ("NOIA", "A CORUÑA"),
    ("OCAÑA", "TOLEDO"),
    ("OLIVENZA", "BADAJOZ"),
    ("OLOT", "GIRONA"),
    ("ONTINYENT", "VALENCIA"),
    ("ORIHUELA", "ALICANTE"),
    ("REUS", "TARRAGONA"),
    ("SAN BARTOLOME DE TIRAJANA", "LAS PALMAS"),
    ("SAN VICENTE DEL RASPEIG", "ALICANTE"),
    ("SANTA CRUZ DE TENERIFE", "SANTA CRUZ DE TENERIFE"),
    ("SIGÜENZA", "GUADALAJARA"),
    ("TORTOSA", "TARRAGONA")
]

In [0]:
df_mapping = spark.createDataFrame(mapping_final, ["ciudad", "provincia"])
display(df_mapping)

ciudad,provincia
A CORUÑA,A CORUÑA
A ESTRADA,PONTEVEDRA
AGUILAR,CORDOBA
ALBACETE,ALBACETE
ALCALA DE GUADAIRA,SEVILLA
ALCALA DE HENARES,MADRID
ALCALA LA REAL,JAEN
ALCARAZ,ALBACETE
ALCAZAR DE SAN JUAN,CIUDAD REAL
ALCAÑIZ,TERUEL
ALCOBENDAS,MADRID
ALCORCON,MADRID
ALCOY,ALICANTE
ALGECIRAS,CADIZ
ALICANTE/ALACANT,ALICANTE
ALMADEN,CIUDAD REAL
ALMAGRO,CIUDAD REAL
ALMANSA,ALBACETE
ALMAZAN,SORIA
ALMENDRALEJO,BADAJOZ
ALMERIA,ALMERIA
ANTEQUERA,MALAGA
ARACENA,HUELVA
ARANDA DE DUERO,BURGOS
ARCOS DE LA FRONTERA,CADIZ
BADALONA,BARCELONA
BAZA,GRANADA
BERJA,ALMERIA
COLLADO VILLALBA,MADRID
CORCUBION,A CORUÑA
CUENCA,CUENCA
DURANGO,BIZKAIA
FONSAGRADA,LUGO
FREGENAL DE LA SIERRA,BADAJOZ
GETAFE,MADRID
GUADIX,GRANADA
HUESCAR,GRANADA
JACA,HUESCA
JEREZ DE LA FRONTERA,CADIZ
LAREDO,CANTABRIA
LEGANES,MADRID
LORCA,MURCIA
MADRID,MADRID
MALAGA,MALAGA
MEDINA DEL CAMPO,VALLADOLID
MERIDA,BADAJOZ
MOTILLA DEL PALANCAR,CUENCA
MURCIA,MURCIA
NAVALMORAL DE LA MATA,CACERES
NEGREIRA,A CORUÑA
NOIA,A CORUÑA
OCAÑA,TOLEDO
OLIVENZA,BADAJOZ
OLOT,GIRONA
ONTINYENT,VALENCIA
ORIHUELA,ALICANTE
REUS,TARRAGONA
SAN BARTOLOME DE TIRAJANA,LAS PALMAS
SAN VICENTE DEL RASPEIG,ALICANTE
SANTA CRUZ DE TENERIFE,SANTA CRUZ DE TENERIFE
SIGÜENZA,GUADALAJARA
TORTOSA,TARRAGONA

In [0]:
dataset_prov = dataset_con_ciudad_norm.join(df_mapping, on="ciudad", how="left")

In [0]:
ciudades_pendientes = (
    dataset_prov
    .filter(F.col("provincia").isNull())
    .select("ciudad")
    .distinct()
    .orderBy("ciudad")
)

display(ciudades_pendientes)

ciudad
""
ALMUÑECAR
ALZIRA
AMPOSTA
AMURRIO
ANDUJAR
AOIZ
ARANJUEZ
ARCHIDONA
ARENAS DE SAN PEDRO
ARENYS DE MAR
AREVALO
ARGANDA DEL REY
ARONA
ARRECIFE
ARUCAS
ARZUA
ASTORGA
AVILA
AVILES
AYAMONTE
AZPEITIA
BADAJOZ
BAENA
BAEZA
BALAGUER
BALMASEDA
BANDE
BARAKALDO
BARBASTRO
BARBATE
BARCELONA
BARCO DE VALDEORRAS
BECERREA
BEJAR
BENAVENTE
BENIDORM
BERGA
BERGARA
BETANZOS
BILBAO
BLANES
BOLTAÑA
BRIVIESCA
BURGO DE OSMA
BURGOS
CABRA
CACERES
CADIZ
CALAHORRA
CALAMOCHA
CALATAYUD
CALDAS DE REIS
CAMBADOS
CANGAS DE MORRAZO
CANGAS DE NARCEA
CANGAS DE ONIS
CARAVACA DE LA CRUZ
CARBALLO
CARLET
CARMONA
CARRION DE LOS CONDES
CARTAGENA
CASAS IBAÑEZ
CASPE
CASTELLON/CASTELLO
CASTRO-URDIALES
CASTROPOL
CASTUERA
CATARROJA
CAZALLA DE LA SIERRA
CAZORLA
CELANOVA
CERDANYOLA DEL VALLES
CERVERA
CERVERA DE PISUERGA
CEUTA
CHANTADA
CHICLANA DE LA FRONTERA
CIEZA
CISTIERNA
CIUDAD REAL
CIUDAD RODRIGO
CIUTADELLA DE MENORCA
COIN
COLMENAR VIEJO
CORDOBA
CORIA
CORIA DEL RIO
CORNELLA DE LLOBREGAT
COSLADA
CUELLAR
DAIMIEL
DAROCA
DENIA
DON BENITO
DONOSTIA-SAN SEBASTIAN
DOS HERMANAS
ECIJA
EIBAR
EIVISSA
EJEA DE LOS CABALLEROS
EL EJIDO
EL PRAT DE LLOBREGAT
EL PUERTO DE SANTA MARIA
EL VENDRELL
ELCHE/ELX
ELDA
ELX
ESPLUGUES DE LLOBREGAT
ESTELLA
ESTEPA
ESTEPONA
FALSET
FERROL
FIGUERES
FRAGA
FUENGIROLA
FUENLABRADA
GANDESA
GANDIA
GAVA
GERNIKA-LUMO
GETXO
GIJON
GIRONA
GRADO
GRANADA
GRANADILLA DE ABONA
GRANOLLERS
GUADALAJARA
GÜIMAR
HARO
HELLIN
HERRERA DEL DUQUE
HUELVA
HUERCAL-OVERA
HUESCA
IBI
ICOD DE LOS VINOS
IGUALADA
ILLESCAS
INCA
IRUN
JAEN
JEREZ DE LOS CABALLEROS
JUMILLA
L'HOSPITALET DE LLOBREGAT
LA ALMUNIA DE DOÑA GODINA
LA BAÑEZA
LA BISBAL D'EMPORDA
LA CAROLINA
LA LINEA DE LA CONCEPCION
LA OROTAVA
LA PALMA DEL CONDADO
LA RODA
LA SEU D'URGELL
LALIN
LANGREO
LAS PALMAS DE GRAN CANARIA
LAVIANA
LEBRIJA
LENA
LEON
LERMA
LINARES
LLANES
LLEIDA
LLERENA
LLIRIA
LOGROSAN
LOGROÑO
LOJA
LORA DEL RIO
LOS LLANOS DE ARIDANE
LUARCA (VALDES)
LUCENA
LUGO
MAJADAHONDA
MANACOR
MANRESA
MANZANARES
MAO/MAHON
MARBELLA
MARCHENA
MARIN
MARTORELL
MARTOS
MASSAMAGRELL
MATARO
MEDINA DE RIOSECO
MEDIO CUDEYO
MELILLA
MIERES
MIRANDA DE EBRO
MISLATA
MOGUER
MOLINA DE ARAGON
MOLINA DE SEGURA
MOLLET DEL VALLEÉS
MONCADA
MONDOÑEDO
MONFORTE DE LEMOS
MONTIJO
MONTILLA
MONTORO
MONZÓN
MORON DE LA FRONTERA
MOSTOLES
MOTRIL
MULA
MUROS
NAVALCARNERO
NOVELDA
NULES
O CARBALLIÑO
O PORRIÑO
ORDES
ORGAZ
ORGIVA
ORTIGUEIRA
OSUNA
OURENSE
OVIEDO
PADRON
PALENCIA
PALMA
PAMPLONA
PAMPLONA/IRUÐA
PARLA
PATERNA
PEÑARANDA DE BRACAMONTE
PEÑARROYA-PUEBLONUEVO
PICASSENT
PIEDRAHITA
PILOÑA-INFIESTO
PLASENCIA
POBRA DE TRIVES
PONFERRADA
PONTEAREAS
PONTEVEDRA
POSADAS
POZOBLANCO
POZUELO DE ALARCON
PRAVIA
PRIEGO DE CORDOBA
PUEBLA DE SANABRIA
PUENTE-GENIL
PUERTO DE LA CRUZ
PUERTO DEL ROSARIO
PUERTO REAL
PUERTOLLANO
PUIGCERDA
PURCHENA
QUART DE POBLET
QUINTANAR DE LA ORDEN
REDONDELA
REINOSA
REQUENA
RIBADAVIA
RIBEIRA
RIPOLL
RONDA
ROQUETAS DE MAR
ROTA
RUBI
SABADELL
SAGUNTO/SAGUNT
SAHAGUN
SALAMANCA
SALAS DE LOS INFANTES
SAN CLEMENTE
SAN CRISTOBAL DE LA LAGUNA
SAN FERNANDO
SAN JAVIER
SAN LORENZO DE EL ESCORIAL
SAN ROQUE
SAN SEBASTIAN DE LA GOMERA
SAN VICENTE DE LA BARQUERA
SANLUCAR DE BARRAMEDA
SANLUCAR LA MAYOR
SANT BOI DE LLOBREGAT
SANT FELIU DE GUIXOLS
SANT FELIU DE LLOBREGAT
SANTA COLOMA DE FARNERS
SANTA COLOMA DE GRAMENET
SANTA CRUZ DE LA PALMA
SANTA FE
SANTA MARIA DE GUIA DE GRAN CANARIA
SANTA MARIA LA REAL DE NIEVA
SANTANDER
SANTIAGO DE COMPOSTELA
SANTOÑA
SARRIA
SEGORBE
SEGOVIA
SEPULVEDA
SEVILLA
SIERO
SOLSONA
SORIA
SUECA
TAFALLA
TALAVERA DE LA REINA
TARANCON
TARAZONA
TARRAGONA
TELDE
TERRASSA
TERUEL
TINEO
TOLEDO
TOLOSA
TOMELLOSO
TORO
TORREJON DE ARDOZ
TORRELAGUNA
TORRELAVEGA
TORREMOLINOS
TORRENT
TORREVIEJA
TORRIJOS
TORROX
TOTANA
TREMP
TRUJILLO
TUDELA
TUI
UBEDA
UBRIQUE
UTRERA
VALDEMORO
VALDEPEÑAS
VALENCIA
VALENCIA DE ALCANTARA
VALLADOLID
VALLS
VALVERDE
VALVERDE DEL CAMINO
VELEZ MALAGA
VELEZ RUBIO
VERA
VERIN
VIC
VIELHA E MIJARAN
VIGO
VILAFRANCA DEL PENEDES
VILAGARCIA DE AROUSA
VILALBA
VILANOVA I LA GELTRU
VILLABLINO
VILLACARRILLO
VILLAFRANCA DE LOS BARROS
VILLAJOYOSA/LA VILA JOIOSA
VILLALPANDO
VILLANUEVA DE LA SERENA
VILLANUEVA DE LOS INFANTES
VILLARCAYO
VILLARREAL/VILA-REAL
VILLARROBLEDO
VILLAVICIOSA
VILLENA
VINAROS
VITIGUDINO
VITORIA-GASTEIZ
VIVEIRO
XATIVA
XINZO DE LIMIA
YECLA
ZAFRA
ZAMORA
ZARAGOZA

In [0]:
display(
    ciudades_pendientes.selectExpr("count(*) as num_ciudades_pendientes")
)

num_ciudades_pendientes
372

In [0]:
# dataset_judicial_provincia = (
#     dataset_prov
#     .filter(F.col("provincia").isNotNull())
#     .groupBy("anio", "provincia")
#     .agg(
#         F.sum("denuncias").alias("denuncias"),
#         F.sum("victimas").alias("victimas"),
#         F.sum("ordenes_proteccion").alias("ordenes_proteccion"),
#         F.sum("quebrantamientos").alias("quebrantamientos")
#     )
#     .orderBy("anio", "provincia")
# )

# display(dataset_judicial_provincia)

In [0]:
# dataset_judicial_provincia.write.mode("overwrite").format("delta").save(
#     "/Volumes/workspace/default/tfm_visnu_raw/dataset_judicial_provincia_delta"
# )

In [0]:
import pandas as pd

ruta_ine = "/Volumes/workspace/default/tfm_visnu_raw/ine_municipios_provincias.xlsx"

xls = pd.ExcelFile(ruta_ine)
print(xls.sheet_names[:10], "...")
print("Número de hojas:", len(xls.sheet_names))

['01', '02', '03', '04', '05', '06', '07', '08', '09', '10'] ...
Número de hojas: 52

In [0]:
dfs_ine = []

for hoja in xls.sheet_names:
    # Leer sin cabecera para capturar provincia y luego reasignar nombres
    temp = pd.read_excel(ruta_ine, sheet_name=hoja, header=None)

    # Provincia está en fila 1, columna 0
    provincia = temp.iloc[1, 0]

    # Encabezados reales están en fila 2
    datos = temp.iloc[2:].copy()
    datos.columns = ["cpro", "cmun", "dc", "ciudad"]
    datos["provincia"] = provincia

    dfs_ine.append(datos)

df_ine_pd = pd.concat(dfs_ine, ignore_index=True)

print(df_ine_pd.shape)
df_ine_pd.head()

(8184, 5)

   cpro  cmun  dc               ciudad    provincia
0  CPRO  CMUN  DC               NOMBRE  Araba/Álava
1    01   051   3  Agurain/Salvatierra  Araba/Álava
2    01   001   4     Alegría-Dulantzi  Araba/Álava
3    01   002   9              Amurrio  Araba/Álava
4    01   049   3                Añana  Araba/Álava

In [0]:
df_ine_pd = df_ine_pd.dropna(subset=["ciudad"]).copy()

# Quitar posibles filas basura repetidas
df_ine_pd = df_ine_pd[df_ine_pd["ciudad"] != "NOMBRE"]

# Pasar todo a string
for col in ["cpro", "cmun", "dc", "ciudad", "provincia"]:
    df_ine_pd[col] = df_ine_pd[col].astype(str).str.strip()

print(df_ine_pd.shape)
df_ine_pd.head()

(8132, 5)

  cpro cmun dc               ciudad    provincia
1   01  051  3  Agurain/Salvatierra  Araba/Álava
2   01  001  4     Alegría-Dulantzi  Araba/Álava
3   01  002  9              Amurrio  Araba/Álava
4   01  049  3                Añana  Araba/Álava
5   01  003  5              Aramaio  Araba/Álava

In [0]:
df_ine = spark.createDataFrame(df_ine_pd)
display(df_ine)

In [0]:
from pyspark.sql import functions as F

df_ine_norm = (
    df_ine
    .withColumn("ciudad", F.upper(F.trim(F.col("ciudad"))))
    .withColumn("ciudad", F.regexp_replace("ciudad", r"\s+", " "))
    .withColumn("ciudad", F.regexp_replace("ciudad", "Á", "A"))
    .withColumn("ciudad", F.regexp_replace("ciudad", "É", "E"))
    .withColumn("ciudad", F.regexp_replace("ciudad", "Í", "I"))
    .withColumn("ciudad", F.regexp_replace("ciudad", "Ó", "O"))
    .withColumn("ciudad", F.regexp_replace("ciudad", "Ú", "U"))
    .withColumn("ciudad", F.regexp_replace("ciudad", "Ü", "U"))
    .withColumn("ciudad", F.regexp_replace("ciudad", "Ñ", "N"))
    .withColumn("provincia", F.upper(F.trim(F.col("provincia"))))
    .withColumn("provincia", F.regexp_replace("provincia", "Á", "A"))
    .withColumn("provincia", F.regexp_replace("provincia", "É", "E"))
    .withColumn("provincia", F.regexp_replace("provincia", "Í", "I"))
    .withColumn("provincia", F.regexp_replace("provincia", "Ó", "O"))
    .withColumn("provincia", F.regexp_replace("provincia", "Ú", "U"))
    .withColumn("provincia", F.regexp_replace("provincia", "Ü", "U"))
    .withColumn("provincia", F.regexp_replace("provincia", "Ñ", "N"))
    .select("ciudad", "provincia")
    .dropDuplicates(["ciudad"])
)

display(df_ine_norm)

ciudad,provincia
ABABUJ,TERUEL
ABADES,SEGOVIA
ABADIA,CACERES
ABADIN,LUGO
ABADINO,BIZKAIA
ABAIGAR,NAVARRA
ABAJAS,BURGOS
ABALOS,LA RIOJA
ABALTZISKETA,GIPUZKOA
ABANADES,GUADALAJARA
ABANILLA,MURCIA
ABANTO,ZARAGOZA
ABANTO Y CIERVANA-ABANTO ZIERBENA,BIZKAIA
ABARAN,MURCIA
ABARCA DE CAMPOS,PALENCIA
ABARZUZA/ABARTZUZA,NAVARRA
ABAURREGAINA/ABAURREA ALTA,NAVARRA
ABAURREPEA/ABAURREA BAJA,NAVARRA
ABEGONDO,A CORUNA
ABEJAR,SORIA
ABEJUELA,TERUEL
ABELLA DE LA CONCA,LLEIDA
ABENGIBRE,ALBACETE
ABENOJAR,CIUDAD REAL
ABERIN,NAVARRA
ABERTURA,CACERES
ABEZAMES,ZAMORA
ABIA DE LA OBISPALIA,CUENCA
ABIA DE LAS TORRES,PALENCIA
ABIEGO,HUESCA
ABIZANDA,HUESCA
ABLA,ALMERIA
ABLANQUE,GUADALAJARA
ABLITAS,NAVARRA
ABRERA,BARCELONA
ABRUCENA,ALMERIA
ABUSEJO,SALAMANCA
"ACEBEDA, LA",MADRID
ACEBEDO,LEON
ACEBO,CACERES
"ACEBRON, EL",CUENCA
ACEDERA,BADAJOZ
ACEHUCHE,CACERES
ACEITUNA,CACERES
ACERED,ZARAGOZA
ACEUCHAL,BADAJOZ
ADAHUESCA,HUESCA
ADALIA,VALLADOLID
ADAMUZ,CORDOBA
ADANERO,AVILA
ADEJE,SANTA CRUZ DE TENERIFE
ADEMUZ,VALENCIA/VALÈNCIA
ADIOS,NAVARRA
ADOBES,GUADALAJARA
ADOR,VALENCIA/VALÈNCIA
ADRA,ALMERIA
ADRADA DE HAZA,BURGOS
ADRADA DE PIRON,SEGOVIA
"ADRADA, LA",AVILA
ADRADAS,SORIA
ADRADOS,SEGOVIA
ADUNA,GIPUZKOA
AGAETE,LAS PALMAS
AGALLAS,SALAMANCA
AGOLADA,PONTEVEDRA
AGON,ZARAGOZA
AGONCILLO,LA RIOJA
AGOST,ALICANTE/ALACANT
AGRAMUNT,LLEIDA
AGREDA,SORIA
AGRES,ALICANTE/ALACANT
AGRON,GRANADA
AGUADULCE,SEVILLA
AGUARON,ZARAGOZA
AGUAS CANDIDAS,BURGOS
AGUASAL,VALLADOLID
AGUATON,TERUEL
AGUAVIVA,TERUEL
AGUDO,CIUDAD REAL
AGUERO,HUESCA
AGUILAFUENTE,SEGOVIA
AGUILAR DE BUREBA,BURGOS
AGUILAR DE CAMPOO,PALENCIA
AGUILAR DE CAMPOS,VALLADOLID
AGUILAR DE CODES,NAVARRA
AGUILAR DE LA FRONTERA,CORDOBA
AGUILAR DE SEGARRA,BARCELONA
AGUILAR DEL ALFAMBRA,TERUEL
AGUILAR DEL RIO ALHAMA,LA RIOJA
AGUILAS,MURCIA
AGUILON,ZARAGOZA
AGUIMES,LAS PALMAS
AGULLANA,GIRONA
AGULLENT,VALENCIA/VALÈNCIA
AGULO,SANTA CRUZ DE TENERIFE
AGURAIN/SALVATIERRA,ARABA/ALAVA
AHIGAL,CACERES
AHIGAL DE LOS ACEITEROS,SALAMANCA
AHIGAL DE VILLARINO,SALAMANCA
AHILLONES,BADAJOZ
AIA,GIPUZKOA
AIBAR/OIBAR,NAVARRA
AIELO DE MALFERIT,VALENCIA/VALÈNCIA
AIELO DE RUGAT,VALENCIA/VALÈNCIA
AIGUAFREDA,BARCELONA
AIGUAMURCIA,TARRAGONA
AIGUAVIVA,GIRONA
AIGUES,ALICANTE/ALACANT
AIN,CASTELLON/CASTELLO
AINSA-SOBRARBE,HUESCA
AINZON,ZARAGOZA
AISA,HUESCA
AITONA,LLEIDA
AIZARNAZABAL,GIPUZKOA
AJALVIR,MADRID
AJAMIL DE CAMEROS,LA RIOJA
AJANGIZ,BIZKAIA
AJOFRIN,TOLEDO
ALACANT/ALICANTE,ALICANTE/ALACANT
ALACON,TERUEL
ALADREN,ZARAGOZA
ALAEJOS,VALLADOLID
ALAGON,ZARAGOZA
ALAGON DEL RIO,CACERES
ALAIOR,ILLES BALEARS
ALAJAR,HUELVA
ALAJERO,SANTA CRUZ DE TENERIFE
ALAMEDA,MALAGA
"ALAMEDA DE GARDON, LA",SALAMANCA
ALAMEDA DE LA SAGRA,TOLEDO
ALAMEDA DEL VALLE,MADRID
ALAMEDILLA,GRANADA
"ALAMEDILLA, LA",SALAMANCA
ALAMILLO,CIUDAD REAL
ALAMINOS,GUADALAJARA
"ALAMO, EL",MADRID
"ALAMUS, ELS",LLEIDA
ALANGE,BADAJOZ
ALANIS,SEVILLA
ALAQUÀS,VALENCIA/VALÈNCIA
ALAR DEL REY,PALENCIA
ALARAZ,SALAMANCA
ALARBA,ZARAGOZA
ALARCON,CUENCA
ALARILLA,GUADALAJARA
ALARO,ILLES BALEARS
ALATOZ,ALBACETE
ALBA,TERUEL
ALBA DE CERRATO,PALENCIA
ALBA DE TORMES,SALAMANCA
ALBA DE YELTES,SALAMANCA
ALBACETE,ALBACETE
"ALBAGES, L'",LLEIDA
ALBAIDA,VALENCIA/VALÈNCIA
ALBAIDA DEL ALJARAFE,SEVILLA
ALBAL,VALENCIA/VALÈNCIA
ALBALA,CACERES
ALBALADEJO,CIUDAD REAL
ALBALADEJO DEL CUENDE,CUENCA
ALBALAT DE LA RIBERA,VALENCIA/VALÈNCIA
ALBALAT DELS SORELLS,VALENCIA/VALÈNCIA
ALBALAT DELS TARONGERS,VALENCIA/VALÈNCIA
ALBALATE DE CINCA,HUESCA
ALBALATE DE LAS NOGUERAS,CUENCA
ALBALATE DE ZORITA,GUADALAJARA
ALBALATE DEL ARZOBISPO,TERUEL
ALBALATILLO,HUESCA
ALBANCHEZ,ALMERIA
ALBANCHEZ DE MAGINA,JAEN
ALBANYÀ,GIRONA
ALBARES,GUADALAJARA
ALBARRACIN,TERUEL
ALBARREAL DE TAJO,TOLEDO
ALBATANA,ALBACETE
ALBATERA,ALICANTE/ALACANT
ALBATÀRREC,LLEIDA
ALBELDA,HUESCA
ALBELDA DE IREGUA,LA RIOJA
ALBENDEA,CUENCA
ALBENDIEGO,GUADALAJARA
ALBENTOSA,TERUEL
"ALBERCA DE ZANCARA, LA",CUENCA
"ALBERCA, LA",SALAMANCA
"ALBERGUERIA DE ARGANAN, LA",SALAMANCA
ALBERIC,VALENCIA/VALÈNCIA
ALBERITE,LA RIOJA
ALBERITE DE SAN JUAN,ZARAGOZA
ALBERO ALTO,HUESCA
ALBERO BAJO,HUESCA
ALBERUELA DE TUBO,HUESCA
ALBESA,LLEIDA
ALBETA,ZARAGOZA
"ALBI, L'",LLEIDA
ALBILLOS,BURGOS
ALBINYANA,TARRAGONA
"ALBIOL, L'",TARRAGONA
ALBIZTUR,GIPUZKOA
ALBOCÀSSER,CASTELLON/CASTELLO
ALBOLODUY,ALMERIA
ALBOLOTE,GRANADA
ALBONDON,GRANADA
ALBONS,GIRONA
ALBORACHE,VALENCIA/VALÈNCIA
ALBORAIA/ALBORAYA,VALENCIA/VALÈNCIA
ALBOREA,ALBACETE
ALBORGE,ZARAGOZA
ALBORNOS,AVILA
ALBOX,ALMERIA
ALBUDEITE,MURCIA
"ALBUERA, LA",BADAJOZ
ALBUIXECH,VALENCIA/VALÈNCIA
ALBUNAN,GRANADA
ALBUNOL,GRANADA
ALBUNUELAS,GRANADA
ALBURQUERQUE,BADAJOZ
ALCABON,TOLEDO
ALCADOZO,ALBACETE
ALCAINE,TERUEL
ALCALA DE EBRO,ZARAGOZA
ALCALA DE GUADAIRA,SEVILLA
ALCALA DE GURREA,HUESCA
ALCALA DE HENARES,MADRID
ALCALA DE LA SELVA,TERUEL
ALCALA DE LA VEGA,CUENCA
ALCALA DE LOS GAZULES,CADIZ
ALCALA DE MONCAYO,ZARAGOZA
ALCALA DEL JUCAR,ALBACETE
ALCALA DEL OBISPO,HUESCA
ALCALA DEL RIO,SEVILLA
ALCALA DEL VALLE,CADIZ
ALCALA LA REAL,JAEN
ALCALALI,ALICANTE/ALACANT
ALCALÀ DE XIVERT,CASTELLON/CASTELLO
ALCAMPELL,HUESCA
ALCANADRE,LA RIOJA
ALCANAR,TARRAGONA
ALCANICES,ZAMORA
ALCANIZ,TERUEL
ALCANIZO,TOLEDO
ALCANO,LLEIDA
ALCANTARA,CACERES
ALCANTARILLA,MURCIA
ALCANTUD,CUENCA
ALCARACEJOS,CORDOBA
ALCARAZ,ALBACETE
ALCARRÀS,LLEIDA
ALCAUCIN,MALAGA
ALCAUDETE,JAEN
ALCAUDETE DE LA JARA,TOLEDO
ALCAZAR DE SAN JUAN,CIUDAD REAL
ALCAZAR DEL REY,CUENCA
ALCAZAREN,VALLADOLID
"ALCAZARES, LOS",MURCIA
ALCOBA,CIUDAD REAL
ALCOBENDAS,MADRID
ALCOCER,GUADALAJARA
ALCOCERO DE MOLA,BURGOS
ALCOHUJATE,CUENCA
ALCOI/ALCOY,ALICANTE/ALACANT
ALCOLEA,ALMERIA
ALCOLEA DE CALATRAVA,CIUDAD REAL
ALCOLEA DE CINCA,HUESCA
ALCOLEA DE LAS PENAS,GUADALAJARA
ALCOLEA DE TAJO,TOLEDO
ALCOLEA DEL PINAR,GUADALAJARA
ALCOLEA DEL RIO,SEVILLA
ALCOLEJA,ALICANTE/ALACANT
ALCOLETGE,LLEIDA
ALCOLLARIN,CACERES
ALCONABA,SORIA
ALCONADA,SALAMANCA
ALCONADA DE MADERUELO,SEGOVIA
ALCONCHEL,BADAJOZ
ALCONCHEL DE ARIZA,ZARAGOZA
ALCONCHEL DE LA ESTRELLA,CUENCA
ALCONERA,BADAJOZ
ALCONTAR,ALMERIA
"ALCORA, L'",CASTELLON/CASTELLO
ALCORCON,MADRID
ALCORISA,TERUEL
ALCOROCHES,GUADALAJARA
ALCOSSER,ALICANTE/ALACANT
ALCOVER,TARRAGONA
ALCUBIERRE,HUESCA
ALCUBILLA DE AVELLANEDA,SORIA
ALCUBILLA DE LAS PENAS,SORIA
ALCUBILLA DE NOGALES,ZAMORA
ALCUBILLAS,CIUDAD REAL
ALCUBLAS,VALENCIA/VALÈNCIA
ALCUDIA,ILLES BALEARS
"ALCUDIA DE CRESPINS, L'",VALENCIA/VALÈNCIA
ALCUDIA DE MONTEAGUD,ALMERIA
ALCUDIA DE VEO,CASTELLON/CASTELLO
"ALCUDIA, L'",VALENCIA/VALÈNCIA
ALCUESCAR,CACERES
ALCÀNTERA DE XUQUER,VALENCIA/VALÈNCIA
ALCÀSSER,VALENCIA/VALÈNCIA
ALDAIA,VALENCIA/VALÈNCIA
ALDEA DE SAN MIGUEL,VALLADOLID
"ALDEA DE SAN NICOLAS, LA",LAS PALMAS
ALDEA DEL CANO,CACERES
ALDEA DEL FRESNO,MADRID
ALDEA DEL OBISPO,SALAMANCA
"ALDEA DEL OBISPO, LA",CACERES
ALDEA DEL REY,CIUDAD REAL
ALDEA EN CABO,TOLEDO
ALDEA REAL,SEGOVIA
"ALDEA, L'",TARRAGONA
ALDEACENTENERA,CACERES
ALDEACIPRESTE,SALAMANCA
ALDEADAVILA DE LA RIBERA,SALAMANCA
ALDEALAFUENTE,SORIA
ALDEALCORVO,SEGOVIA
ALDEALENGUA,SALAMANCA
ALDEALENGUA DE PEDRAZA,SEGOVIA
ALDEALENGUA DE SANTA MARIA,SEGOVIA
ALDEALICES,SORIA
ALDEALPOZO,SORIA
ALDEALSENOR,SORIA
ALDEAMAYOR DE SAN MARTIN,VALLADOLID
ALDEANUEVA DE BARBARROYA,TOLEDO
ALDEANUEVA DE EBRO,LA RIOJA
ALDEANUEVA DE FIGUEROA,SALAMANCA
ALDEANUEVA DE GUADALAJARA,GUADALAJARA
ALDEANUEVA DE LA SERREZUELA,SEGOVIA
ALDEANUEVA DE LA SIERRA,SALAMANCA
ALDEANUEVA DE LA VERA,CACERES
ALDEANUEVA DE SAN BARTOLOME,TOLEDO
ALDEANUEVA DE SANTA CRUZ,AVILA
ALDEANUEVA DEL CAMINO,CACERES
ALDEANUEVA DEL CODONAL,SEGOVIA
ALDEAQUEMADA,JAEN
ALDEARRODRIGO,SALAMANCA
ALDEARRUBIA,SALAMANCA
ALDEASECA,AVILA
ALDEASECA DE ALBA,SALAMANCA
ALDEASECA DE LA FRONTERA,SALAMANCA
ALDEASONA,SEGOVIA
ALDEATEJADA,SALAMANCA
ALDEAVIEJA DE TORMES,SALAMANCA
ALDEHORNO,SEGOVIA
ALDEHUELA DE LA BOVEDA,SALAMANCA
ALDEHUELA DE LIESTOS,ZARAGOZA
ALDEHUELA DE PERIANEZ,SORIA
ALDEHUELA DE YELTES,SALAMANCA
ALDEHUELA DEL CODONAL,SEGOVIA
ALDEHUELA DEL JERTE,CACERES
"ALDEHUELA, LA",AVILA
"ALDEHUELAS, LAS",SORIA
ALDEIRE,GRANADA
ALDEONTE,SEGOVIA
ALDOVER,TARRAGONA
ALEDO,MURCIA
ALEGIA,GIPUZKOA
ALEGRIA-DULANTZI,ARABA/ALAVA
"ALEIXAR, L'",TARRAGONA
ALELLA,BARCELONA
ALENTISQUE,SORIA
ALERRE,HUESCA
ALESANCO,LA RIOJA
ALESON,LA RIOJA
ALFACAR,GRANADA
ALFAFAR,VALENCIA/VALÈNCIA
ALFAFARA,ALICANTE/ALACANT
ALFAJARIN,ZARAGOZA
ALFAMBRA,TERUEL
ALFAMEN,ZARAGOZA
ALFANTEGA,HUESCA
ALFARA DE CARLES,TARRAGONA
ALFARA DE LA BARONIA,VALENCIA/VALÈNCIA
ALFARA DEL PATRIARCA,VALENCIA/VALÈNCIA
ALFARAZ DE SAYAGO,ZAMORA
ALFARB,VALENCIA/VALÈNCIA
ALFARNATE,MALAGA
ALFARNATEJO,MALAGA
ALFARO,LA RIOJA
ALFARRASI,VALENCIA/VALÈNCIA
ALFARRÀS,LLEIDA
ALFAUIR,VALENCIA/VALÈNCIA
ALFES,LLEIDA
ALFONDEGUILLA,CASTELLON/CASTELLO
ALFORJA,TARRAGONA
ALFORQUE,ZARAGOZA
ALFOZ,LUGO
ALFOZ DE BRICIA,BURGOS
ALFOZ DE LLOREDO,CANTABRIA
ALFOZ DE QUINTANADUENAS,BURGOS
ALFOZ DE SANTA GADEA,BURGOS
"ALFÀS DEL PI, L'",ALICANTE/ALACANT
"ALGABA, LA",SEVILLA
ALGADEFE,LEON
ALGAIDA,ILLES BALEARS
ALGAMITAS,SEVILLA
ALGAR,CADIZ
ALGAR DE MESA,GUADALAJARA
ALGAR DE PALÀNCIA,VALENCIA/VALÈNCIA
ALGARINEJO,GRANADA
ALGARRA,CUENCA
ALGARROBO,MALAGA
ALGATOCIN,MALAGA
ALGECIRAS,CADIZ
ALGEMESI,VALENCIA/VALÈNCIA
ALGERRI,LLEIDA
ALGETE,MADRID
ALGIMIA D'ALFARA,VALENCIA/VALÈNCIA
ALGIMIA DE ALMONACID,CASTELLON/CASTELLO
ALGINET,VALENCIA/VALÈNCIA
ALGODONALES,CADIZ
ALGODRE,ZAMORA
ALGORA,GUADALAJARA
ALGORFA,ALICANTE/ALACANT
ALGUAIRE,LLEIDA
ALGUAZAS,MURCIA
ALGUENA,ALICANTE/ALACANT
ALHABIA,ALMERIA
ALHAMA DE ALMERIA,ALMERIA
ALHAMA DE ARAGON,ZARAGOZA
ALHAMA DE GRANADA,GRANADA
ALHAMA DE MURCIA,MURCIA
ALHAMBRA,CIUDAD REAL
ALHAURIN DE LA TORRE,MALAGA
ALHAURIN EL GRANDE,MALAGA
ALHENDIN,GRANADA
ALHONDIGA,GUADALAJARA
ALIA,CACERES
ALIAGA,TERUEL
ALIAGUILLA,CUENCA
ALICUN,ALMERIA
ALICUN DE ORTEGA,GRANADA
ALIJA DEL INFANTADO,LEON
ALINS,LLEIDA
ALIO,TARRAGONA
ALIQUE,GUADALAJARA
ALISEDA,CACERES
ALIUD,SORIA
ALJARAQUE,HUELVA
ALJUCEN,BADAJOZ
ALKIZA,GIPUZKOA
ALLANDE,ASTURIAS
ALLARIZ,OURENSE
ALLEPUZ,TERUEL
ALLER,ASTURIAS
ALLIN/ALLIN,NAVARRA
ALLO,NAVARRA
ALLOZA,TERUEL
ALLUEVA,TERUEL
ALMACELLES,LLEIDA
ALMACHAR,MALAGA
ALMADEN,CIUDAD REAL
ALMADEN DE LA PLATA,SEVILLA
ALMADENEJOS,CIUDAD REAL
ALMADRONES,GUADALAJARA
ALMAGRO,CIUDAD REAL
ALMAJANO,SORIA
ALMALUEZ,SORIA
ALMANSA,ALBACETE
ALMANZA,LEON
ALMARAZ,CACERES
ALMARAZ DE DUERO,ZAMORA
"ALMARCHA, LA",CUENCA
ALMARGEN,MALAGA
ALMARZA,SORIA
ALMARZA DE CAMEROS,LA RIOJA
ALMASSORA,CASTELLON/CASTELLO
ALMATRET,LLEIDA
ALMAZAN,SORIA
ALMAZUL,SORIA
ALMEDIJAR,CASTELLON/CASTELLO
ALMEDINA,CIUDAD REAL
ALMEDINILLA,CORDOBA
ALMEGIJAR,GRANADA
ALMEIDA DE SAYAGO,ZAMORA
ALMENAR,LLEIDA
ALMENAR DE SORIA,SORIA
ALMENARA,CASTELLON/CASTELLO
ALMENARA DE ADAJA,VALLADOLID
ALMENARA DE TORMES,SALAMANCA
ALMENDRA,SALAMANCA
ALMENDRAL,BADAJOZ
ALMENDRAL DE LA CANADA,TOLEDO
ALMENDRALEJO,BADAJOZ
"ALMENDRO, EL",HUELVA
ALMENDROS,CUENCA
ALMENSILLA,SEVILLA
ALMERIA,ALMERIA
ALMISERÀ,VALENCIA/VALÈNCIA
ALMOCHUEL,ZARAGOZA
ALMOCITA,ALMERIA
ALMODOVAR DEL CAMPO,CIUDAD REAL
ALMODOVAR DEL PINAR,CUENCA
ALMODOVAR DEL RIO,CORDOBA
ALMOGIA,MALAGA
ALMOGUERA,GUADALAJARA
ALMOHAJA,TERUEL
ALMOHARIN,CACERES
ALMOINES,VALENCIA/VALÈNCIA
"ALMOLDA, LA",ZARAGOZA
ALMONACID DE LA CUBA,ZARAGOZA
ALMONACID DE LA SIERRA,ZARAGOZA
ALMONACID DE TOLEDO,TOLEDO
ALMONACID DE ZORITA,GUADALAJARA
ALMONACID DEL MARQUESADO,CUENCA
ALMONASTER LA REAL,HUELVA
ALMONTE,HUELVA
ALMORADI,ALICANTE/ALACANT
ALMOROX,TOLEDO
ALMOSTER,TARRAGONA
ALMUDAINA,ALICANTE/ALACANT
ALMUDEVAR,HUESCA
ALMUNECAR,GRANADA
"ALMUNIA DE DONA GODINA, LA",ZARAGOZA
ALMUNIA DE SAN JUAN,HUESCA
ALMUNIENTE,HUESCA
ALMURADIEL,CIUDAD REAL
ALMUSSAFES,VALENCIA/VALÈNCIA
ALMÀSSERA,VALENCIA/VALÈNCIA
ALOBRAS,TERUEL
ALOCEN,GUADALAJARA
ALONSOTEGI,BIZKAIA
ALORA,MALAGA
ALOSNO,HUELVA
ALOVERA,GUADALAJARA
ALOZAINA,MALAGA
ALP,GIRONA
ALPANDEIRE,MALAGA
ALPANSEQUE,SORIA
ALPARTIR,ZARAGOZA
ALPEDRETE,MADRID
ALPENES,TERUEL
ALPENS,BARCELONA
ALPERA,ALBACETE
ALPICAT,LLEIDA
ALPUENTE,VALENCIA/VALÈNCIA
ALPUJARRA DE LA SIERRA,GRANADA
"ALQUERIA D'ASNAR, L'",ALICANTE/ALACANT
"ALQUERIA DE LA COMTESSA, L'",VALENCIA/VALÈNCIA
"ALQUERIES, LES/ALQUERIAS DEL NINO PERDIDO",CASTELLON/CASTELLO
ALQUEZAR,HUESCA
ALQUIFE,GRANADA
ALSODUX,ALMERIA
ALT ÀNEU,LLEIDA
ALTABLE,BURGOS
ALTAFULLA,TARRAGONA
ALTAREJOS,CUENCA
ALTEA,ALICANTE/ALACANT
ALTORRICON,HUESCA
"ALTOS, LOS",BURGOS
ALTSASU/ALSASUA,NAVARRA
ALTURA,CASTELLON/CASTELLO
ALTZAGA,GIPUZKOA
ALTZO,GIPUZKOA
ALUSTANTE,GUADALAJARA
ALZIRA,VALENCIA/VALÈNCIA
ALÀS I CERC,LLEIDA
ALÒS DE BALAGUER,LLEIDA
AMAVIDA,AVILA
AMAYUELAS DE ARRIBA,PALENCIA
AMBEL,ZARAGOZA
AMBITE,MADRID
AMER,GIRONA
AMES,A CORUNA
AMESCOA BAJA,NAVARRA
"AMETLLA DE MAR, L'",TARRAGONA
"AMETLLA DEL VALLÈS, L'",BARCELONA
AMEYUGO,BURGOS
AMEZKETA,GIPUZKOA
AMIEVA,ASTURIAS
AMOEIRO,OURENSE
AMOREBIETA-ETXANO,BIZKAIA
AMOROTO,BIZKAIA
"AMPOLLA, L'",TARRAGONA
AMPOSTA,TARRAGONA
AMPUDIA,PALENCIA
AMPUERO,CANTABRIA
AMURRIO,ARABA/ALAVA
AMUSCO,PALENCIA
AMUSQUILLO,VALLADOLID
ANADON,TERUEL
ANANA,ARABA/ALAVA
ANAYA,SEGOVIA
ANAYA DE ALBA,SALAMANCA
ANCHUELO,MADRID
ANCHURAS,CIUDAD REAL
ANCIN/ANTZIN,NAVARRA
ANDAVIAS,ZAMORA
ANDILLA,VALENCIA/VALÈNCIA
ANDOAIN,GIPUZKOA
ANDORRA,TERUEL
ANDOSILLA,NAVARRA
ANDRATX,ILLES BALEARS
ANDUJAR,JAEN
ANE,SEGOVIA
ANENTO,ZARAGOZA
ANGLESOLA,LLEIDA
ANGLÈS,GIRONA
ANGON,GUADALAJARA
ANGUCIANA,LA RIOJA
ANGUES,HUESCA
ANGUIANO,LA RIOJA
ANGUITA,GUADALAJARA
ANGUIX,BURGOS
ANIEVAS,CANTABRIA
ANINON,ZARAGOZA
ANNA,VALENCIA/VALÈNCIA
ANOETA,GIPUZKOA
ANON DE MONCAYO,ZARAGOZA
ANORA,CORDOBA
ANORBE,NAVARRA
ANOVER DE TAJO,TOLEDO
ANOVER DE TORMES,SALAMANCA
ANQUELA DEL DUCADO,GUADALAJARA
ANQUELA DEL PEDREGAL,GUADALAJARA
ANSO,HUESCA
ANSOAIN/ANTSOAIN,NAVARRA
ANTAS,ALMERIA
ANTAS DE ULLA,LUGO
ANTELLA,VALENCIA/VALÈNCIA
ANTEQUERA,MALAGA
ANTIGUA,LAS PALMAS
"ANTIGUA, LA",LEON
ANTIGUEDAD,PALENCIA
ANTILLON,HUESCA
ANTZUOLA,GIPUZKOA
ANUE,NAVARRA
AOIZ/AGOITZ,NAVARRA
ARABAYONA DE MOGICA,SALAMANCA
ARACENA,HUELVA
ARAFO,SANTA CRUZ DE TENERIFE
ARAGUES DEL PUERTO,HUESCA
ARAHAL,SEVILLA
ARAHUETES,SEGOVIA
ARAITZ,NAVARRA
ARAKALDO,BIZKAIA
ARAKIL,NAVARRA
ARAMA,GIPUZKOA
ARAMAIO,ARABA/ALAVA
ARANARACHE/ARANARATXE,NAVARRA
ARANCON,SORIA
ARANDA DE DUERO,BURGOS
ARANDA DE MONCAYO,ZARAGOZA
ARANDIGA,ZARAGOZA
ARANDILLA,BURGOS
ARANDILLA DEL ARROYO,CUENCA
ARANGA,A CORUNA
ARANGUREN,NAVARRA
ARANJUEZ,MADRID
ARANO,NAVARRA
ARANTZA,NAVARRA
ARANTZAZU,BIZKAIA
ARANUEL,CASTELLON/CASTELLO
ARANZUEQUE,GUADALAJARA
ARAPILES,SALAMANCA
ARAS,NAVARRA
ARAS DE LOS OLMOS,VALENCIA/VALÈNCIA
ARAUZO DE MIEL,BURGOS
ARAUZO DE SALCE,BURGOS
ARAUZO DE TORRE,BURGOS
ARBANCON,GUADALAJARA
ARBECA,LLEIDA
ARBETETA,GUADALAJARA
ARBIZU,NAVARRA
ARBO,PONTEVEDRA
ARBOLEAS,ALMERIA
ARBOLI,TARRAGONA
"ARBOÇ, L'",TARRAGONA
ARBUCIES,GIRONA
ARCAS,CUENCA
ARCE/ARTZI,NAVARRA
ARCEDIANO,SALAMANCA
ARCENILLAS,ZAMORA
ARCHENA,MURCIA
ARCHEZ,MALAGA
ARCHIDONA,MALAGA
ARCICOLLAR,TOLEDO
"ARCO, EL",SALAMANCA
ARCONADA,PALENCIA
ARCONES,SEGOVIA
ARCOS,BURGOS
ARCOS DE JALON,SORIA
ARCOS DE LA FRONTERA,CADIZ
ARCOS DE LA POLVOROSA,ZAMORA
ARCOS DE LA SIERRA,CUENCA
ARCOS DE LAS SALINAS,TERUEL
"ARCOS, LOS",NAVARRA
ARDALES,MALAGA
ARDISA,ZARAGOZA
ARDON,LEON
AREATZA,BIZKAIA
ARELLANO,NAVARRA
AREN,HUESCA
"ARENAL, EL",AVILA
ARENALES DE SAN GREGORIO,CIUDAD REAL
ARENAS,MALAGA
ARENAS DE IGUNA,CANTABRIA
ARENAS DE SAN JUAN,CIUDAD REAL
ARENAS DE SAN PEDRO,AVILA
ARENAS DEL REY,GRANADA
ARENILLAS,SORIA
ARENILLAS DE RIOPISUERGA,BURGOS
ARENS DE LLEDO,TERUEL
ARENYS DE MAR,BARCELONA
ARENYS DE MUNT,BARCELONA
ARENZANA DE ABAJO,LA RIOJA
ARENZANA DE ARRIBA,LA RIOJA
ARES,A CORUNA
ARES DEL MAESTRAT,CASTELLON/CASTELLO
ARESO,NAVARRA
ARETXABALETA,GIPUZKOA
AREVALILLO,AVILA
AREVALILLO DE CEGA,SEGOVIA
AREVALO,AVILA
AREVALO DE LA SIERRA,SORIA
ARGAMASILLA DE ALBA,CIUDAD REAL
ARGAMASILLA DE CALATRAVA,CIUDAD REAL
ARGANDA DEL REY,MADRID
ARGANIN,ZAMORA
ARGANZA,LEON
ARGAVIESO,HUESCA
ARGECILLA,GUADALAJARA
ARGELAGUER,GIRONA
ARGELITA,CASTELLON/CASTELLO
ARGENTE,TERUEL
"ARGENTERA, L'",TARRAGONA
ARGENTONA,BARCELONA
ARGENÇOLA,BARCELONA
ARGES,TOLEDO
ARGONOS,CANTABRIA
ARGUEDAS,NAVARRA
ARGUIS,HUESCA
ARGUISUELAS,CUENCA
ARGUJILLO,ZAMORA
ARIA,NAVARRA
ARIANY,ILLES BALEARS
ARIBE,NAVARRA
ARICO,SANTA CRUZ DE TENERIFE
ARIJA,BURGOS
ARINO,TERUEL
ARIZA,ZARAGOZA
ARJONA,JAEN
ARJONILLA,JAEN
ARLANZON,BURGOS
ARMALLONES,GUADALAJARA
ARMANANZAS,NAVARRA
"ARMENTERA, L'",GIRONA
ARMENTEROS,SALAMANCA
ARMILLA,GRANADA
ARMINON,ARABA/ALAVA
ARMUNA,SEGOVIA
ARMUNA DE ALMANZORA,ALMERIA
ARMUNA DE TAJUNA,GUADALAJARA
ARNEDILLO,LA RIOJA
ARNEDO,LA RIOJA
ARNES,TARRAGONA
"ARNOIA, A",OURENSE
ARNUERO,CANTABRIA
AROCHE,HUELVA
ARONA,SANTA CRUZ DE TENERIFE
ARQUILLINOS,ZAMORA
ARQUILLOS,JAEN
ARRABALDE,ZAMORA
ARRAIA-MAEZTU,ARABA/ALAVA
ARRANCACEPAS,CUENCA
ARRANKUDIAGA-ZOLLO,BIZKAIA
ARRASATE/MONDRAGON,GIPUZKOA
ARRATZU,BIZKAIA
ARRATZUA-UBARRUNDIA,ARABA/ALAVA
ARRAYA DE OCA,BURGOS
ARRECIFE,LAS PALMAS
ARREDONDO,CANTABRIA
ARRES,LLEIDA
ARRIATE,MALAGA
ARRIETA,BIZKAIA
ARRIGORRIAGA,BIZKAIA
ARROBA DE LOS MONTES,CIUDAD REAL
ARRONIZ,NAVARRA
ARROYO DE LA ENCOMIENDA,VALLADOLID
ARROYO DE LA LUZ,CACERES
ARROYO DE LAS FRAGUAS,GUADALAJARA
ARROYO DE SAN SERVAN,BADAJOZ
ARROYO DEL OJANCO,JAEN
ARROYOMOLINOS,CACERES
ARROYOMOLINOS DE LA VERA,CACERES
ARROYOMOLINOS DE LEON,HUELVA
ARRUAZU,NAVARRA
ARRUBAL,LA RIOJA
ARSÈGUEL,LLEIDA
ARTAJONA,NAVARRA
ARTANA,CASTELLON/CASTELLO
ARTAZU,NAVARRA
ARTEA,BIZKAIA
ARTEIXO,A CORUNA
ARTENARA,LAS PALMAS
ARTES,BARCELONA
ARTESA DE LLEIDA,LLEIDA
ARTESA DE SEGRE,LLEIDA
ARTIEDA,ZARAGOZA
ARTZENTALES,BIZKAIA
ARTZINIEGA,ARABA/ALAVA
ARTÀ,ILLES BALEARS
ARUCAS,LAS PALMAS
ARZUA,A CORUNA
ASCO,TARRAGONA
ASIN,ZARAGOZA
ASPA,LLEIDA
ASPARIEGOS,ZAMORA
ASPARRENA,ARABA/ALAVA
ASPE,ALICANTE/ALACANT
ASTEASU,GIPUZKOA
ASTIGARRAGA,GIPUZKOA
"ASTILLERO, EL",CANTABRIA
ASTORGA,LEON
ASTUDILLO,PALENCIA
ASTURIANOS,ZAMORA
ATAJATE,MALAGA
ATALAYA,BADAJOZ
ATALAYA DEL CANAVATE,CUENCA
"ATALAYA, LA",SALAMANCA
ATANZON,GUADALAJARA
ATAPUERCA,BURGOS
ATAQUINES,VALLADOLID
ATARFE,GRANADA
ATAUN,GIPUZKOA
"ATAZAR, EL",MADRID
ATEA,ZARAGOZA
ATECA,ZARAGOZA
ATETZ,NAVARRA
ATIENZA,GUADALAJARA
ATXONDO,BIZKAIA
ATZENETA D'ALBAIDA,VALENCIA/VALÈNCIA
ATZENETA DEL MAESTRAT,CASTELLON/CASTELLO
"ATZUBIA, L'",ALICANTE/ALACANT
AULESTI,BIZKAIA
AUNON,GUADALAJARA
AURITZ/BURGUETE,NAVARRA
AUSEJO,LA RIOJA
AUSEJO DE LA SIERRA,SORIA
"AUSINES, LOS",BURGOS
AUTILLA DEL PINO,PALENCIA
AUTILLO DE CAMPOS,PALENCIA
AUTOL,LA RIOJA
AVEINTE,AVILA
AVELLANEDA,AVILA
"AVELLANES I SANTA LINYA, LES",LLEIDA
AVELLANOSA DE MUNO,BURGOS
AVILA,AVILA
AVILES,ASTURIAS
AVINYO,BARCELONA
AVINYONET DE PUIGVENTOS,GIRONA
AVINYONET DEL PENEDÈS,BARCELONA
AVION,OURENSE
AVIÀ,BARCELONA
AYALA/AIARA,ARABA/ALAVA
AYAMONTE,HUELVA
AYEGUI/AIEGI,NAVARRA
AYERBE,HUESCA
AYLLON,SEGOVIA
AYNA,ALBACETE
AYODAR,CASTELLON/CASTELLO
AYOO DE VIDRIALES,ZAMORA
AYORA,VALENCIA/VALÈNCIA
AYUELA,PALENCIA
AZAGRA,NAVARRA
AZAILA,TERUEL
AZANUY-ALINS,HUESCA
AZARA,HUESCA
AZKOITIA,GIPUZKOA
AZLOR,HUESCA
AZNALCAZAR,SEVILLA
AZNALCOLLAR,SEVILLA
AZOFRA,LA RIOJA
AZPEITIA,GIPUZKOA
AZUAGA,BADAJOZ
AZUARA,ZARAGOZA
AZUEBAR,CASTELLON/CASTELLO
AZUELO,NAVARRA
AZUQUECA DE HENARES,GUADALAJARA
AZUTAN,TOLEDO
BABILAFUENTE,SALAMANCA
BACARES,ALMERIA
BADAJOZ,BADAJOZ
BADALONA,BARCELONA
BADARAN,LA RIOJA
BADENAS,TERUEL
BADIA DEL VALLÈS,BARCELONA
BADOLATOSA,SEVILLA
BADULES,ZARAGOZA
BAELLS,HUESCA
BAENA,CORDOBA
BAEZA,JAEN
BAGUENA,TERUEL
BAGUES,ZARAGOZA
BAGÀ,BARCELONA
BAHABON,VALLADOLID
BAHABON DE ESGUEVA,BURGOS
BAIDES,GUADALAJARA
BAILEN,JAEN
BAILO,HUESCA
BAIONA,PONTEVEDRA
BAIX PALLARS,LLEIDA
BAKAIKU,NAVARRA
BAKIO,BIZKAIA
BALAGUER,LLEIDA
BALANEGRA,ALMERIA
BALAZOTE,ALBACETE
"BALBASES, LOS",BURGOS
BALBOA,LEON
BALCONCHAN,ZARAGOZA
BALDELLOU,HUESCA
BALEIRA,LUGO
BALENYÀ,BARCELONA
BALIARRAIN,GIPUZKOA
"BALLESTERO, EL",ALBACETE
BALLESTEROS DE CALATRAVA,CIUDAD REAL
BALLOBAR,HUESCA
BALMASEDA,BIZKAIA
BALONES,ALICANTE/ALACANT
BALSA DE VES,ALBACETE
BALSARENY,BARCELONA
BALTANAS,PALENCIA
BALTAR,OURENSE
"BANA, A",A CORUNA
BANARES,LA RIOJA
BANASTAS,HUESCA
BANDE,OURENSE
"BANEZA, LA",LEON
BANOBAREZ,SALAMANCA
BANON,TERUEL
BANOS DE EBRO/MANUETA,ARABA/ALAVA
BANOS DE LA ENCINA,JAEN
BANOS DE MOLGAS,OURENSE
BANOS DE MONTEMAYOR,CACERES
BANOS DE RIO TOBIA,LA RIOJA
BANOS DE RIOJA,LA RIOJA
BANOS DE TAJO,GUADALAJARA
BANOS DE VALDEARADOS,BURGOS
BANUELOS,GUADALAJARA
BANUELOS DE BUREBA,BURGOS
BANYALBUFAR,ILLES BALEARS
BANYERES DE MARIOLA,ALICANTE/ALACANT
BANYERES DEL PENEDÈS,TARRAGONA
BANYOLES,GIRONA
BAQUERIN DE CAMPOS,PALENCIA
BARAJAS DE MELO,CUENCA
BARAKALDO,BIZKAIA
BARALLA,LUGO
BARANAIN/BARANAIN,NAVARRA
BARAONA,SORIA
BARASOAIN,NAVARRA
BARBADAS,OURENSE
BARBADILLO,SALAMANCA

In [0]:
dataset_con_ciudad_norm = (
    dataset_con_ciudad
    .withColumn("ciudad", F.upper(F.trim(F.col("ciudad"))))
    .withColumn("ciudad", F.regexp_replace("ciudad", r"\s+", " "))
    .withColumn("ciudad", F.regexp_replace("ciudad", "Á", "A"))
    .withColumn("ciudad", F.regexp_replace("ciudad", "É", "E"))
    .withColumn("ciudad", F.regexp_replace("ciudad", "Í", "I"))
    .withColumn("ciudad", F.regexp_replace("ciudad", "Ó", "O"))
    .withColumn("ciudad", F.regexp_replace("ciudad", "Ú", "U"))
    .withColumn("ciudad", F.regexp_replace("ciudad", "Ü", "U"))
    .withColumn("ciudad", F.regexp_replace("ciudad", "Ñ", "N"))
)

In [0]:
dataset_prov_auto = dataset_con_ciudad_norm.join(df_ine_norm, on="ciudad", how="left")

In [0]:
ciudades_pendientes_auto = (
    dataset_prov_auto
    .filter(F.col("provincia").isNull())
    .select("ciudad")
    .distinct()
    .orderBy("ciudad")
)

display(ciudades_pendientes_auto)

ciudad
""
A CORUNA
A ESTRADA
AGUILAR
ALCOY
ALICANTE/ALACANT
AOIZ
BARCO DE VALDEORRAS
BURGO DE OSMA
CANGAS DE MORRAZO
CANGAS DE NARCEA
CASAS IBANEZ
CASTELLON/CASTELLO
CERDANYOLA DEL VALLES
CORNELLA DE LLOBREGAT
DONOSTIA-SAN SEBASTIAN
EL EJIDO
EL PRAT DE LLOBREGAT
EL PUERTO DE SANTA MARIA
EL VENDRELL
ELCHE/ELX
ELX
ESTELLA
FONSAGRADA
GAVA
L'HOSPITALET DE LLOBREGAT
LA ALMUNIA DE DONA GODINA
LA BANEZA
LA BISBAL D'EMPORDA
LA CAROLINA
LA LINEA DE LA CONCEPCION
LA OROTAVA
LA PALMA DEL CONDADO
LA RODA
LA SEU D'URGELL
LAS PALMAS DE GRAN CANARIA
LOS LLANOS DE ARIDANE
LUARCA (VALDES)
MAO/MAHON
MOLLET DEL VALLEES
MONCADA
O CARBALLINO
O PORRINO
PAMPLONA
PAMPLONA/IRUÐA
PILONA-INFIESTO
POBRA DE TRIVES
PUENTE-GENIL
PUIGCERDA
SAGUNTO/SAGUNT
SAN VICENTE DEL RASPEIG
VALENCIA
VELEZ MALAGA
VELEZ RUBIO
VILAFRANCA DEL PENEDES
VILLAJOYOSA/LA VILA JOIOSA
VILLARCAYO
VILLARREAL/VILA-REAL
VINAROS
XATIVA

In [0]:
display(
    ciudades_pendientes_auto.selectExpr("count(*) as num_ciudades_pendientes")
)

num_ciudades_pendientes
60

In [0]:
mapping_manual_residual = [
    ("A CORUNA", "A CORUNA"),
    ("A ESTRADA", "PONTEVEDRA"),
    ("AGUILAR", "CORDOBA"),
    ("ALCOY", "ALICANTE"),
    ("ALICANTE/ALACANT", "ALICANTE"),
    ("AOIZ", "NAVARRA"),
    ("BARCO DE VALDEORRAS", "OURENSE"),
    ("BURGO DE OSMA", "SORIA"),
    ("CANGAS DE MORRAZO", "PONTEVEDRA"),
    ("CANGAS DE NARCEA", "ASTURIAS"),
    ("CASAS IBANEZ", "ALBACETE"),
    ("CASTELLON/CASTELLO", "CASTELLON"),
    ("CERDANYOLA DEL VALLES", "BARCELONA"),
    ("CORNELLA DE LLOBREGAT", "BARCELONA"),
    ("DONOSTIA-SAN SEBASTIAN", "GIPUZKOA"),
    ("EL EJIDO", "ALMERIA"),
    ("EL PRAT DE LLOBREGAT", "BARCELONA"),
    ("EL PUERTO DE SANTA MARIA", "CADIZ"),
    ("EL VENDRELL", "TARRAGONA"),
    ("ELCHE/ELX", "ALICANTE"),
    ("ELX", "ALICANTE"),
    ("ESTELLA", "NAVARRA"),
    ("FONSAGRADA", "LUGO"),
    ("GAVA", "BARCELONA"),
    ("L'HOSPITALET DE LLOBREGAT", "BARCELONA"),
    ("LA ALMUNIA DE DONA GODINA", "ZARAGOZA"),
    ("LA BANEZA", "LEON"),
    ("LA BISBAL D'EMPORDA", "GIRONA"),
    ("LA CAROLINA", "JAEN"),
    ("LA LINEA DE LA CONCEPCION", "CADIZ"),
    ("LA OROTAVA", "SANTA CRUZ DE TENERIFE"),
    ("LA PALMA DEL CONDADO", "HUELVA"),
    ("LA RODA", "ALBACETE"),
    ("LA SEU D'URGELL", "LLEIDA"),
    ("LAS PALMAS DE GRAN CANARIA", "LAS PALMAS"),
    ("LOS LLANOS DE ARIDANE", "SANTA CRUZ DE TENERIFE"),
    ("LUARCA (VALDES)", "ASTURIAS"),
    ("MAO/MAHON", "ILLES BALEARS"),
    ("MOLLET DEL VALLEES", "BARCELONA"),
    ("MONCADA", "VALENCIA"),
    ("O CARBALLINO", "OURENSE"),
    ("O PORRINO", "PONTEVEDRA"),
    ("PAMPLONA", "NAVARRA"),
    ("PAMPLONA/IRUNA", "NAVARRA"),
    ("PILONA-INFIESTO", "ASTURIAS"),
    ("POBRA DE TRIVES", "OURENSE"),
    ("PUENTE-GENIL", "CORDOBA"),
    ("PUIGCERDA", "GIRONA"),
    ("SAGUNTO/SAGUNT", "VALENCIA"),
    ("SAN VICENTE DEL RASPEIG", "ALICANTE"),
    ("VALENCIA", "VALENCIA"),
    ("VELEZ MALAGA", "MALAGA"),
    ("VELEZ RUBIO", "ALMERIA"),
    ("VILAFRANCA DEL PENEDES", "BARCELONA"),
    ("VILLAJOYOSA/LA VILA JOIOSA", "ALICANTE"),
    ("VILLARCAYO", "BURGOS"),
    ("VILLARREAL/VILA-REAL", "CASTELLON"),
    ("VINAROS", "CASTELLON"),
    ("XATIVA", "VALENCIA")
]

In [0]:
df_mapping_manual = spark.createDataFrame(
    mapping_manual_residual,
    ["ciudad", "provincia_manual"]
)

display(df_mapping_manual)

ciudad,provincia_manual
A CORUNA,A CORUNA
A ESTRADA,PONTEVEDRA
AGUILAR,CORDOBA
ALCOY,ALICANTE
ALICANTE/ALACANT,ALICANTE
AOIZ,NAVARRA
BARCO DE VALDEORRAS,OURENSE
BURGO DE OSMA,SORIA
CANGAS DE MORRAZO,PONTEVEDRA
CANGAS DE NARCEA,ASTURIAS
CASAS IBANEZ,ALBACETE
CASTELLON/CASTELLO,CASTELLON
CERDANYOLA DEL VALLES,BARCELONA
CORNELLA DE LLOBREGAT,BARCELONA
DONOSTIA-SAN SEBASTIAN,GIPUZKOA
EL EJIDO,ALMERIA
EL PRAT DE LLOBREGAT,BARCELONA
EL PUERTO DE SANTA MARIA,CADIZ
EL VENDRELL,TARRAGONA
ELCHE/ELX,ALICANTE
ELX,ALICANTE
ESTELLA,NAVARRA
FONSAGRADA,LUGO
GAVA,BARCELONA
L'HOSPITALET DE LLOBREGAT,BARCELONA
LA ALMUNIA DE DONA GODINA,ZARAGOZA
LA BANEZA,LEON
LA BISBAL D'EMPORDA,GIRONA
LA CAROLINA,JAEN
LA LINEA DE LA CONCEPCION,CADIZ
LA OROTAVA,SANTA CRUZ DE TENERIFE
LA PALMA DEL CONDADO,HUELVA
LA RODA,ALBACETE
LA SEU D'URGELL,LLEIDA
LAS PALMAS DE GRAN CANARIA,LAS PALMAS
LOS LLANOS DE ARIDANE,SANTA CRUZ DE TENERIFE
LUARCA (VALDES),ASTURIAS
MAO/MAHON,ILLES BALEARS
MOLLET DEL VALLEES,BARCELONA
MONCADA,VALENCIA
O CARBALLINO,OURENSE
O PORRINO,PONTEVEDRA
PAMPLONA,NAVARRA
PAMPLONA/IRUNA,NAVARRA
PILONA-INFIESTO,ASTURIAS
POBRA DE TRIVES,OURENSE
PUENTE-GENIL,CORDOBA
PUIGCERDA,GIRONA
SAGUNTO/SAGUNT,VALENCIA
SAN VICENTE DEL RASPEIG,ALICANTE
VALENCIA,VALENCIA
VELEZ MALAGA,MALAGA
VELEZ RUBIO,ALMERIA
VILAFRANCA DEL PENEDES,BARCELONA
VILLAJOYOSA/LA VILA JOIOSA,ALICANTE
VILLARCAYO,BURGOS
VILLARREAL/VILA-REAL,CASTELLON
VINAROS,CASTELLON
XATIVA,VALENCIA

In [0]:
dataset_prov_final_map = (
    dataset_prov_auto
    .join(df_mapping_manual, on="ciudad", how="left")
    .withColumn(
        "provincia_final",
        F.coalesce(F.col("provincia_manual"), F.col("provincia"))
    )
)

In [0]:
ciudades_pendientes_finales = (
    dataset_prov_final_map
    .filter(F.col("provincia_final").isNull())
    .select("ciudad")
    .distinct()
    .orderBy("ciudad")
)

display(ciudades_pendientes_finales)

display(
    ciudades_pendientes_finales.selectExpr("count(*) as num_ciudades_pendientes_finales")
)

ciudad
""
PAMPLONA/IRUÐA

num_ciudades_pendientes_finales
2

In [0]:
display(
    dataset_prov_final_map
    .filter(F.col("provincia_final").isNull())
    .select("ciudad")
    .distinct()
)

ciudad
PAMPLONA/IRUÐA
""

In [0]:
df_mapping_fix = spark.createDataFrame(
    [
        ("PAMPLONA/IRUÐA", "NAVARRA"),
        ("PAMPLONA/IRUÑA", "NAVARRA"),
        ("PAMPLONA/IRUNA", "NAVARRA")
    ],
    ["ciudad", "provincia_fix"]
)

In [0]:
dataset_prov_final_map = (
    dataset_prov_final_map
    .drop("provincia_fix")
    .join(df_mapping_fix, on="ciudad", how="left")
    .withColumn(
        "provincia_final",
        F.coalesce(F.col("provincia_final"), F.col("provincia_fix"))
    )
    .drop("provincia_fix")
)

In [0]:
ciudades_pendientes_finales = (
    dataset_prov_final_map
    .filter(
        (F.col("provincia_final").isNull()) &
        (F.col("ciudad").isNotNull()) &
        (F.trim(F.col("ciudad")) != "")
    )
    .select("ciudad")
    .distinct()
    .orderBy("ciudad")
)

display(ciudades_pendientes_finales)

display(
    ciudades_pendientes_finales.selectExpr("count(*) as num_ciudades_pendientes_finales")
)

num_ciudades_pendientes_finales
0

In [0]:
dataset_judicial_provincia = (
    dataset_prov_final_map
    .filter(F.col("provincia_final").isNotNull())
    .groupBy("anio", F.col("provincia_final").alias("provincia"))
    .agg(
        F.sum("denuncias").alias("denuncias"),
        F.sum("victimas").alias("victimas"),
        F.sum("ordenes_proteccion").alias("ordenes_proteccion"),
        F.sum("quebrantamientos").alias("quebrantamientos")
    )
    .orderBy("anio", "provincia")
)

display(dataset_judicial_provincia)

anio,provincia,denuncias,victimas,ordenes_proteccion,quebrantamientos
2014,A CORUNA,1928.0,1928.0,412.0,57.0
2014,ALBACETE,808.0,808.0,332.0,28.0
2014,ALICANTE,3294.0,3294.0,1083.0,70.0
2014,ALICANTE/ALACANT,3061.0,3061.0,708.0,26.0
2014,ALMERIA,2084.0,2084.0,641.0,191.0
2014,ARABA/ALAVA,663.0,663.0,80.0,0.0
2014,ASTURIAS,2394.0,2394.0,741.0,51.0
2014,AVILA,274.0,274.0,122.0,0.0
2014,BADAJOZ,1302.0,1302.0,482.0,17.0
2014,BARCELONA,12383.0,12383.0,3551.0,256.0
2014,BIZKAIA,2243.0,2243.0,414.0,134.0
2014,BURGOS,680.0,680.0,188.0,8.0
2014,CACERES,631.0,631.0,222.0,39.0
2014,CADIZ,3806.0,3806.0,957.0,136.0
2014,CANTABRIA,1230.0,1230.0,380.0,10.0
2014,CASTELLON,1254.0,1254.0,379.0,30.0
2014,CASTELLON/CASTELLO,257.0,257.0,86.0,3.0
2014,CIUDAD AUTONOMA DE CEUTA,239.0,239.0,34.0,2.0
2014,CIUDAD AUTONOMA DE MELILLA,303.0,303.0,49.0,24.0
2014,CIUDAD REAL,1149.0,1149.0,478.0,116.0
2014,CORDOBA,1653.0,1653.0,472.0,30.0
2014,CUENCA,361.0,361.0,157.0,31.0
2014,GIPUZKOA,1084.0,1084.0,284.0,22.0
2014,GIRONA,2473.0,2473.0,939.0,70.0
2014,GRANADA,3447.0,3447.0,415.0,65.0
2014,GUADALAJARA,560.0,560.0,192.0,9.0
2014,HUELVA,1600.0,1600.0,478.0,31.0
2014,HUESCA,293.0,293.0,117.0,10.0
2014,ILLES BALEARS,4687.0,4687.0,567.0,119.0
2014,JAEN,1705.0,1705.0,347.0,101.0
2014,LA RIOJA,549.0,549.0,180.0,13.0
2014,LAS PALMAS,3845.0,3845.0,1126.0,46.0
2014,LEON,920.0,920.0,175.0,30.0
2014,LLEIDA,897.0,897.0,261.0,12.0
2014,LUGO,545.0,545.0,186.0,14.0
2014,MADRID,17818.0,17818.0,5041.0,522.0
2014,MALAGA,5923.0,5923.0,1121.0,249.0
2014,MURCIA,5039.0,5039.0,1231.0,140.0
2014,NAVARRA,1328.0,1328.0,288.0,20.0
2014,OURENSE,506.0,506.0,154.0,37.0
2014,PALENCIA,181.0,181.0,101.0,8.0
2014,PONTEVEDRA,2230.0,2230.0,575.0,25.0
2014,SALAMANCA,342.0,342.0,113.0,8.0
2014,SANTA CRUZ DE TENERIFE,3091.0,3091.0,1071.0,82.0
2014,SEGOVIA,216.0,216.0,75.0,0.0
2014,SEVILLA,6692.0,6692.0,1849.0,387.0
2014,SORIA,142.0,142.0,73.0,0.0
2014,TARRAGONA,2268.0,2268.0,755.0,55.0
2014,TERUEL,157.0,157.0,41.0,1.0
2014,TOLEDO,1405.0,1405.0,422.0,14.0
2014,VALENCIA,5081.0,5081.0,922.0,93.0
2014,VALENCIA/VALÈNCIA,3101.0,3101.0,758.0,112.0
2014,VALLADOLID,2062.0,2062.0,442.0,0.0
2014,ZAMORA,315.0,315.0,65.0,21.0
2014,ZARAGOZA,2791.0,2791.0,564.0,24.0
2015,A CORUNA,1925.0,1788.0,498.0,58.0
2015,ALBACETE,797.0,791.0,357.0,35.0
2015,ALICANTE,3584.0,2926.0,1069.0,79.0
2015,ALICANTE/ALACANT,3176.0,3175.0,773.0,72.0
2015,ALMERIA,2306.0,2068.0,757.0,235.0
2015,ARABA/ALAVA,826.0,825.0,98.0,0.0
2015,ASTURIAS,2266.0,2146.0,758.0,111.0
2015,AVILA,283.0,283.0,111.0,3.0
2015,BADAJOZ,1605.0,1592.0,441.0,34.0
2015,BARCELONA,13457.0,13206.0,3856.0,487.0
2015,BIZKAIA,2266.0,2242.0,423.0,139.0
2015,BURGOS,621.0,614.0,195.0,11.0
2015,CACERES,831.0,808.0,263.0,12.0
2015,CADIZ,3766.0,3735.0,1107.0,287.0
2015,CANTABRIA,1327.0,1256.0,352.0,26.0
2015,CASTELLON,1240.0,1240.0,290.0,67.0
2015,CASTELLON/CASTELLO,285.0,245.0,96.0,0.0
2015,CIUDAD AUTONOMA DE CEUTA,151.0,151.0,52.0,0.0
2015,CIUDAD AUTONOMA DE MELILLA,291.0,291.0,78.0,31.0
2015,CIUDAD REAL,1194.0,1055.0,514.0,74.0
2015,CORDOBA,1638.0,1631.0,501.0,34.0
2015,CUENCA,437.0,435.0,192.0,28.0
2015,GIPUZKOA,1140.0,1140.0,298.0,59.0
2015,GIRONA,2796.0,2734.0,796.0,163.0
2015,GRANADA,3486.0,3191.0,801.0,59.0
2015,GUADALAJARA,669.0,669.0,266.0,17.0
2015,HUELVA,1616.0,1616.0,515.0,92.0
2015,HUESCA,303.0,294.0,155.0,8.0
2015,ILLES BALEARS,4658.0,4576.0,666.0,207.0
2015,JAEN,1482.0,1476.0,631.0,126.0
2015,LA RIOJA,616.0,615.0,258.0,20.0
2015,LAS PALMAS,3994.0,3860.0,1117.0,43.0
2015,LEON,984.0,951.0,203.0,25.0
2015,LLEIDA,904.0,899.0,294.0,36.0
2015,LUGO,535.0,529.0,219.0,19.0
2015,MADRID,17241.0,15879.0,4797.0,553.0
2015,MALAGA,6177.0,5995.0,1563.0,222.0
2015,MURCIA,5034.0,4854.0,1465.0,97.0
2015,NAVARRA,1191.0,1173.0,291.0,41.0
2015,OURENSE,505.0,498.0,250.0,11.0
2015,PALENCIA,204.0,143.0,66.0,8.0
2015,PONTEVEDRA,2245.0,2196.0,597.0,66.0
2015,SALAMANCA,284.0,284.0,96.0,24.0
2015,SANTA CRUZ DE TENERIFE,3764.0,3655.0,1124.0,232.0
2015,SEGOVIA,224.0,224.0,72.0,0.0
2015,SEVILLA,7111.0,6514.0,2021.0,346.0
2015,SORIA,118.0,118.0,64.0,1.0
2015,TARRAGONA,2170.0,2110.0,814.0,76.0
2015,TERUEL,143.0,143.0,66.0,0.0
2015,TOLEDO,1537.0,1537.0,494.0,40.0
2015,VALENCIA,5171.0,4914.0,1100.0,213.0
2015,VALENCIA/VALÈNCIA,3218.0,3038.0,936.0,240.0
2015,VALLADOLID,1589.0,1589.0,428.0,9.0
2015,ZAMORA,337.0,336.0,126.0,24.0
2015,ZARAGOZA,2189.0,2186.0,612.0,36.0
2016,A CORUNA,2193.0,1696.0,614.0,131.0
2016,ALBACETE,817.0,817.0,290.0,46.0
2016,ALICANTE,3810.0,2934.0,1084.0,279.0
2016,ALICANTE/ALACANT,3686.0,3676.0,740.0,210.0
2016,ALMERIA,2675.0,2504.0,986.0,261.0
2016,ARABA/ALAVA,884.0,884.0,91.0,0.0
2016,ASTURIAS,2617.0,2584.0,783.0,252.0
2016,AVILA,241.0,241.0,112.0,3.0
2016,BADAJOZ,1755.0,1743.0,499.0,90.0
2016,BARCELONA,14382.0,13858.0,3662.0,1168.0
2016,BIZKAIA,2573.0,2585.0,387.0,222.0
2016,BURGOS,763.0,579.0,237.0,38.0
2016,CACERES,878.0,790.0,278.0,47.0
2016,CADIZ,3741.0,3641.0,1184.0,237.0
2016,CANTABRIA,1507.0,1206.0,336.0,116.0
2016,CASTELLON,1427.0,1410.0,358.0,98.0
2016,CASTELLON/CASTELLO,205.0,205.0,75.0,10.0
2016,CIUDAD AUTONOMA DE CEUTA,174.0,174.0,131.0,35.0
2016,CIUDAD AUTONOMA DE MELILLA,411.0,411.0,71.0,14.0
2016,CIUDAD REAL,1659.0,1467.0,597.0,259.0
2016,CORDOBA,1511.0,1511.0,446.0,113.0
2016,CUENCA,369.0,366.0,127.0,43.0
2016,GIPUZKOA,1307.0,1302.0,291.0,135.0
2016,GIRONA,2828.0,2554.0,700.0,446.0
2016,GRANADA,3883.0,3827.0,1028.0,116.0
2016,GUADALAJARA,667.0,667.0,227.0,55.0
2016,HUELVA,1932.0,1904.0,496.0,180.0
2016,HUESCA,287.0,287.0,160.0,18.0
2016,ILLES BALEARS,5268.0,5193.0,755.0,409.0
2016,JAEN,1698.0,1687.0,685.0,148.0
2016,LA RIOJA,690.0,443.0,305.0,54.0
2016,LAS PALMAS,4803.0,4736.0,1053.0,130.0
2016,LEON,1010.0,1006.0,220.0,111.0
2016,LLEIDA,1048.0,1020.0,305.0,104.0
2016,LUGO,691.0,671.0,216.0,32.0
2016,MADRID,19855.0,18044.0,4965.0,1834.0
2016,MALAGA,6722.0,6134.0,1506.0,508.0
2016,MURCIA,6302.0,5915.0,1751.0,262.0
2016,NAVARRA,1502.0,1494.0,359.0,207.0
2016,OURENSE,589.0,587.0,360.0,40.0
2016,PALENCIA,256.0,154.0,113.0,17.0
2016,PONTEVEDRA,2210.0,2150.0,501.0,89.0
2016,SALAMANCA,313.0,299.0,127.0,57.0
2016,SANTA CRUZ DE TENERIFE,3959.0,3871.0,1291.0,280.0
2016,SEGOVIA,259.0,259.0,65.0,22.0
2016,SEVILLA,7250.0,6582.0,1914.0,501.0
2016,SORIA,108.0,108.0,69.0,16.0
2016,TARRAGONA,2067.0,1945.0,904.0,305.0
2016,TERUEL,191.0,186.0,71.0,3.0
2016,TOLEDO,1219.0,1135.0,509.0,82.0
2016,VALENCIA,6172.0,5704.0,1221.0,647.0
2016,VALENCIA/VALÈNCIA,3482.0,3471.0,1019.0,604.0
2016,VALLADOLID,1374.0,1374.0,445.0,47.0
2016,ZAMORA,309.0,309.0,135.0,19.0
2016,ZARAGOZA,2684.0,2649.0,726.0,190.0
2017,A CORUNA,2442.0,2066.0,721.0,227.0
2017,ALBACETE,820.0,811.0,253.0,48.0
2017,ALICANTE,4691.0,4231.0,1074.0,277.0
2017,ALICANTE/ALACANT,4304.0,4260.0,922.0,253.0
2017,ALMERIA,3299.0,3246.0,1099.0,265.0
2017,ARABA/ALAVA,935.0,978.0,118.0,37.0
2017,ASTURIAS,2560.0,2354.0,780.0,302.0
2017,AVILA,300.0,312.0,109.0,0.0
2017,BADAJOZ,1870.0,1790.0,561.0,136.0
2017,BARCELONA,16225.0,15510.0,3725.0,1331.0
2017,BIZKAIA,2926.0,2931.0,473.0,179.0
2017,BURGOS,845.0,842.0,242.0,39.0
2017,CACERES,920.0,874.0,231.0,139.0
2017,CADIZ,4038.0,3900.0,1454.0,302.0
2017,CANTABRIA,1908.0,1717.0,296.0,224.0
2017,CASTELLON,1615.0,1429.0,361.0,198.0
2017,CASTELLON/CASTELLO,263.0,258.0,107.0,21.0
2017,CIUDAD AUTONOMA DE CEUTA,443.0,327.0,168.0,38.0
2017,CIUDAD AUTONOMA DE MELILLA,384.0,329.0,87.0,15.0
2017,CIUDAD REAL,1441.0,1363.0,473.0,179.0
2017,CORDOBA,1803.0,1774.0,434.0,103.0
2017,CUENCA,353.0,338.0,113.0,22.0
2017,GIPUZKOA,1331.0,1315.0,281.0,54.0
2017,GIRONA,3080.0,2974.0,642.0,246.0
2017,GRANADA,4082.0,3703.0,1024.0,131.0
2017,GUADALAJARA,558.0,553.0,242.0,44.0
2017,HUELVA,2394.0,2344.0,525.0,159.0
2017,HUESCA,402.0,398.0,169.0,20.0
2017,ILLES BALEARS,5412.0,5368.0,906.0,351.0
2017,JAEN,2000.0,1945.0,551.0,192.0
2017,LA RIOJA,727.0,718.0,243.0,50.0
2017,LAS PALMAS,4966.0,4991.0,880.0,168.0
2017,LEON,1024.0,1028.0,327.0,120.0
2017,LLEIDA,1244.0,1158.0,301.0,103.0
2017,LUGO,729.0,661.0,216.0,119.0
2017,MADRID,24838.0,23226.0,5415.0,2570.0
2017,MALAGA,7854.0,8098.0,1462.0,1357.0
2017,MURCIA,7839.0,6443.0,1555.0,1281.0
2017,NAVARRA,1836.0,1803.0,365.0,212.0
2017,OURENSE,747.0,776.0,422.0,121.0
2017,PALENCIA,404.0,326.0,66.0,5.0
2017,PONTEVEDRA,2518.0,2498.0,569.0,182.0
2017,SALAMANCA,666.0,609.0,149.0,45.0
2017,SANTA CRUZ DE TENERIFE,4037.0,3884.0,1245.0,302.0
2017,SEGOVIA,330.0,320.0,64.0,2.0
2017,SEVILLA,9101.0,8876.0,1934.0,615.0
2017,SORIA,137.0,131.0,78.0,13.0
2017,TARRAGONA,3352.0,3177.0,933.0,245.0
2017,TERUEL,200.0,199.0,69.0,9.0
2017,TOLEDO,1931.0,1823.0,512.0,202.0
2017,VALENCIA,6669.0,6234.0,1134.0,798.0
2017,VALENCIA/VALÈNCIA,4387.0,4156.0,988.0,719.0
2017,VALLADOLID,1395.0,1294.0,410.0,63.0
2017,ZAMORA,309.0,305.0,152.0,11.0
2017,ZARAGOZA,3258.0,3215.0,547.0,357.0
2018,A CORUNA,2652.0,2206.0,767.0,294.0
2018,ALBACETE,901.0,846.0,344.0,89.0
2018,ALICANTE,4623.0,4550.0,1113.0,449.0
2018,ALICANTE/ALACANT,4223.0,4182.0,938.0,246.0
2018,ALMERIA,4352.0,3283.0,1378.0,818.0
2018,ARABA/ALAVA,940.0,934.0,147.0,41.0
2018,ASTURIAS,2957.0,2560.0,800.0,454.0
2018,AVILA,321.0,356.0,98.0,47.0
2018,BADAJOZ,1708.0,1559.0,537.0,143.0
2018,BARCELONA,16243.0,14949.0,3687.0,1351.0
2018,BIZKAIA,3248.0,3287.0,311.0,197.0
2018,BURGOS,793.0,788.0,237.0,33.0
2018,CACERES,762.0,739.0,297.0,93.0
2018,CADIZ,4156.0,4286.0,1272.0,559.0
2018,CANTABRIA,2000.0,2038.0,352.0,193.0
2018,CASTELLON,1457.0,1339.0,405.0,67.0
2018,CASTELLON/CASTELLO,294.0,291.0,96.0,41.0
2018,CIUDAD AUTONOMA DE CEUTA,280.0,280.0,137.0,0.0
2018,CIUDAD AUTONOMA DE MELILLA,449.0,449.0,21.0,64.0
2018,CIUDAD REAL,1722.0,1615.0,435.0,223.0
2018,CORDOBA,1826.0,1849.0,406.0,122.0
2018,CUENCA,415.0,392.0,166.0,14.0
2018,GIPUZKOA,1452.0,1430.0,285.0,162.0
2018,GIRONA,3037.0,2920.0,588.0,333.0
2018,GRANADA,3528.0,3332.0,1046.0,118.0
2018,GUADALAJARA,770.0,760.0,224.0,100.0
2018,HUELVA,2216.0,2240.0,745.0,54.0
2018,HUESCA,441.0,422.0,150.0,17.0
2018,ILLES BALEARS,5352.0,5825.0,982.0,411.0
2018,JAEN,2031.0,1971.0,504.0,261.0
2018,LA RIOJA,839.0,834.0,307.0,64.0
2018,LAS PALMAS,4573.0,4737.0,786.0,241.0
2018,LEON,1002.0,1027.0,262.0,88.0
2018,LLEIDA,1529.0,1304.0,296.0,131.0
2018,LUGO,709.0,714.0,196.0,96.0
2018,MADRID,25241.0,23666.0,5492.0,3528.0
2018,MALAGA,7978.0,8342.0,1401.0,1431.0
2018,MURCIA,8250.0,6345.0,1648.0,1292.0
2018,NAVARRA,1887.0,1828.0,368.0,268.0
2018,OURENSE,806.0,826.0,533.0,199.0
2018,PALENCIA,307.0,302.0,70.0,17.0
2018,PONTEVEDRA,2370.0,2437.0,525.0,175.0
2018,SALAMANCA,655.0,550.0,136.0,73.0
2018,SANTA CRUZ DE TENERIFE,3769.0,3729.0,1413.0,197.0
2018,SEGOVIA,352.0,327.0,58.0,1.0
2018,SEVILLA,7745.0,7558.0,1853.0,627.0
2018,SORIA,137.0,129.0,73.0,8.0
2018,TARRAGONA,3165.0,2962.0,808.0,261.0
2018,TERUEL,228.0,229.0,58.0,6.0
2018,TOLEDO,1864.0,1708.0,602.0,151.0
2018,VALENCIA,6835.0,6360.0,1204.0,921.0
2018,VALENCIA/VALÈNCIA,4764.0,4446.0,1233.0,740.0
2018,VALLADOLID,1360.0,1202.0,410.0,121.0
2018,ZAMORA,314.0,315.0,143.0,35.0
2018,ZARAGOZA,3384.0,3213.0,507.0,377.0
2019,A CORUNA,2788.0,2355.0,782.0,404.0
2019,ALBACETE,969.0,943.0,371.0,76.0
2019,ALICANTE,4839.0,4828.0,1373.0,644.0
2019,ALICANTE/ALACANT,4607.0,4461.0,866.0,520.0
2019,ALMERIA,3859.0,3355.0,1616.0,544.0
2019,ARABA/ALAVA,990.0,985.0,131.0,50.0
2019,ASTURIAS,2744.0,2643.0,847.0,391.0
2019,AVILA,428.0,416.0,132.0,45.0
2019,BADAJOZ,1676.0,1634.0,611.0,154.0
2019,BARCELONA,15203.0,14848.0,3783.0,1259.0
2019,BIZKAIA,3245.0,3035.0,491.0,308.0
2019,BURGOS,875.0,875.0,271.0,81.0
2019,CACERES,837.0,841.0,237.0,146.0
2019,CADIZ,4485.0,3978.0,1227.0,844.0
2019,CANTABRIA,2004.0,1965.0,279.0,210.0
2019,CASTELLON,1903.0,1900.0,552.0,167.0
2019,CASTELLON/CASTELLO,0.0,0.0,0.0,0.0
2019,CIUDAD AUTONOMA DE CEUTA,264.0,264.0,114.0,0.0
2019,CIUDAD AUTONOMA DE MELILLA,388.0,378.0,36.0,30.0
2019,CIUDAD REAL,1744.0,1725.0,485.0,209.0
2019,CORDOBA,1933.0,1923.0,431.0,95.0
2019,CUENCA,584.0,581.0,189.0,74.0
2019,GIPUZKOA,1696.0,1693.0,212.0,26.0
2019,GIRONA,3574.0,3253.0,726.0,340.0
2019,GRANADA,3783.0,3716.0,887.0,127.0
2019,GUADALAJARA,948.0,912.0,292.0,178.0
2019,HUELVA,2327.0,2217.0,555.0,64.0
2019,HUESCA,414.0,371.0,225.0,36.0
2019,ILLES BALEARS,6493.0,6315.0,1268.0,482.0
2019,JAEN,2074.0,1952.0,405.0,341.0
2019,LA RIOJA,822.0,808.0,228.0,58.0
2019,LAS PALMAS,5433.0,5405.0,937.0,216.0
2019,LEON,938.0,935.0,223.0,103.0
2019,LLEIDA,1528.0,1465.0,278.0,106.0
2019,LUGO,753.0,754.0,247.0,129.0
2019,MADRID,24498.0,23340.0,5497.0,3423.0
2019,MALAGA,8130.0,8004.0,1470.0,991.0
2019,MURCIA,6426.0,6364.0,1589.0,466.0
2019,NAVARRA,1957.0,1919.0,393.0,295.0
2019,OURENSE,664.0,660.0,363.0,97.0
2019,PALENCIA,323.0,323.0,80.0,59.0
2019,PONTEVEDRA,2399.0,2284.0,630.0,107.0
2019,SALAMANCA,508.0,447.0,137.0,46.0
2019,SANTA CRUZ DE TENERIFE,4353.0,4368.0,1530.0,156.0
2019,SEGOVIA,421.0,422.0,71.0,2.0
2019,SEVILLA,7386.0,7416.0,1739.0,631.0
2019,SORIA,158.0,161.0,70.0,15.0
2019,TARRAGONA,3067.0,3047.0,941.0,355.0
2019,TERUEL,204.0,204.0,88.0,6.0
2019,TOLEDO,1806.0,1701.0,548.0,162.0
2019,VALENCIA,6792.0,6508.0,1273.0,987.0
2019,VALENCIA/VALÈNCIA,4958.0,4448.0,1371.0,727.0
2019,VALLADOLID,1323.0,1292.0,423.0,111.0
2019,ZAMORA,295.0,291.0,123.0,54.0
2019,ZARAGOZA,3626.0,2882.0,701.0,414.0
2020,A CORUNA,2524.0,2528.0,1004.0,498.0
2020,ALBACETE,943.0,926.0,399.0,80.0
2020,ALICANTE,4275.0,4250.0,1339.0,547.0
2020,ALICANTE/ALACANT,3880.0,3697.0,700.0,389.0
2020,ALMERIA,3365.0,3015.0,1159.0,367.0
2020,ARABA/ALAVA,889.0,889.0,84.0,60.0
2020,ASTURIAS,2548.0,2490.0,697.0,478.0
2020,AVILA,291.0,291.0,91.0,38.0
2020,BADAJOZ,1471.0,1467.0,480.0,134.0
2020,BARCELONA,13540.0,13376.0,3259.0,1555.0
2020,BIZKAIA,3028.0,2935.0,304.0,112.0
2020,BURGOS,768.0,768.0,262.0,77.0
2020,CACERES,791.0,759.0,189.0,196.0
2020,CADIZ,5027.0,4090.0,1214.0,1343.0
2020,CANTABRIA,1668.0,1668.0,285.0,198.0
2020,CASTELLON,1979.0,1979.0,412.0,264.0
2020,CASTELLON/CASTELLO,0.0,0.0,0.0,0.0
2020,CIUDAD AUTONOMA DE CEUTA,228.0,228.0,90.0,0.0
2020,CIUDAD AUTONOMA DE MELILLA,323.0,317.0,88.0,20.0
2020,CIUDAD REAL,1500.0,1500.0,318.0,251.0
2020,CORDOBA,2039.0,2024.0,477.0,194.0
2020,CUENCA,421.0,421.0,156.0,39.0
2020,GIPUZKOA,1438.0,1438.0,174.0,60.0
2020,GIRONA,3144.0,3029.0,672.0,276.0
2020,GRANADA,3981.0,3967.0,1176.0,241.0
2020,GUADALAJARA,949.0,949.0,189.0,117.0
2020,HUELVA,2403.0,2346.0,577.0,147.0
2020,HUESCA,385.0,382.0,206.0,24.0
2020,ILLES BALEARS,5838.0,5506.0,1179.0,465.0
2020,JAEN,1889.0,1767.0,365.0,279.0
2020,LA RIOJA,768.0,768.0,256.0,65.0
2020,LAS PALMAS,4982.0,4932.0,1050.0,204.0
2020,LEON,879.0,866.0,290.0,107.0
2020,LLEIDA,1405.0,1405.0,277.0,180.0
2020,LUGO,682.0,680.0,214.0,149.0
2020,MADRID,20865.0,20267.0,4837.0,2509.0
2020,MALAGA,6659.0,6493.0,1196.0,748.0
2020,MURCIA,6103.0,5997.0,1275.0,726.0
2020,NAVARRA,1796.0,1773.0,386.0,298.0
2020,OURENSE,789.0,789.0,231.0,294.0
2020,PALENCIA,251.0,251.0,72.0,46.0
2020,PONTEVEDRA,2102.0,2076.0,615.0,105.0
2020,SALAMANCA,432.0,432.0,93.0,20.0
2020,SANTA CRUZ DE TENERIFE,3944.0,3923.0,1178.0,240.0
2020,SEGOVIA,518.0,518.0,56.0,47.0
2020,SEVILLA,5487.0,5487.0,1674.0,604.0
2020,SORIA,175.0,175.0,64.0,24.0
2020,TARRAGONA,2605.0,2605.0,716.0,358.0
2020,TERUEL,165.0,165.0,60.0,4.0
2020,TOLEDO,1728.0,1620.0,529.0,220.0
2020,VALENCIA,6136.0,5649.0,1226.0,1020.0
2020,VALENCIA/VALÈNCIA,5019.0,4657.0,991.0,900.0
2020,VALLADOLID,1155.0,1155.0,373.0,83.0
2020,ZAMORA,290.0,288.0,127.0,39.0
2020,ZARAGOZA,2727.0,2160.0,497.0,306.0
2021,A CORUNA,2587.0,2560.0,904.0,292.0
2021,ALBACETE,1040.0,1027.0,350.0,124.0
2021,ALICANTE,4573.0,4563.0,1458.0,576.0
2021,ALICANTE/ALACANT,4029.0,4007.0,826.0,424.0
2021,ALMERIA,3300.0,3082.0,853.0,392.0
2021,ARABA/ALAVA,820.0,820.0,118.0,34.0
2021,ASTURIAS,2419.0,2407.0,635.0,336.0
2021,AVILA,398.0,398.0,155.0,42.0
2021,BADAJOZ,1746.0,1743.0,611.0,105.0
2021,BARCELONA,14944.0,14715.0,3494.0,1626.0
2021,BIZKAIA,3092.0,3092.0,425.0,176.0
2021,BURGOS,857.0,851.0,297.0,97.0
2021,CACERES,846.0,846.0,237.0,123.0
2021,CADIZ,5206.0,4333.0,1328.0,1320.0
2021,CANTABRIA,1898.0,1819.0,367.0,199.0
2021,CASTELLON,1876.0,1768.0,428.0,362.0
2021,CASTELLON/CASTELLO,0.0,0.0,0.0,0.0
2021,CIUDAD AUTONOMA DE CEUTA,275.0,275.0,100.0,6.0
2021,CIUDAD AUTONOMA DE MELILLA,356.0,356.0,66.0,23.0
2021,CIUDAD REAL,1548.0,1548.0,378.0,231.0
2021,CORDOBA,2389.0,2388.0,429.0,206.0
2021,CUENCA,428.0,428.0,156.0,31.0
2021,GIPUZKOA,1445.0,1442.0,251.0,135.0
2021,GIRONA,3561.0,3559.0,635.0,400.0
2021,GRANADA,4950.0,4946.0,1396.0,378.0
2021,GUADALAJARA,1433.0,1433.0,206.0,284.0
2021,HUELVA,2518.0,2449.0,686.0,130.0
2021,HUESCA,473.0,465.0,170.0,40.0
2021,ILLES BALEARS,6363.0,6058.0,911.0,544.0
2021,JAEN,1999.0,1974.0,387.0,264.0
2021,LA RIOJA,823.0,821.0,330.0,65.0
2021,LAS PALMAS,5033.0,5002.0,1028.0,215.0
2021,LEON,882.0,881.0,213.0,167.0
2021,LLEIDA,1527.0,1527.0,359.0,164.0
2021,LUGO,720.0,711.0,196.0,169.0
2021,MADRID,23619.0,23075.0,5207.0,3553.0
2021,MALAGA,6861.0,6851.0,1186.0,669.0
2021,MURCIA,6750.0,6736.0,1525.0,688.0
2021,NAVARRA,1630.0,1630.0,358.0,233.0
2021,OURENSE,741.0,737.0,172.0,284.0
2021,PALENCIA,323.0,323.0,121.0,87.0
2021,PONTEVEDRA,2211.0,2211.0,554.0,138.0
2021,SALAMANCA,385.0,385.0,91.0,31.0
2021,SANTA CRUZ DE TENERIFE,3969.0,3969.0,856.0,288.0
2021,SEGOVIA,538.0,538.0,63.0,165.0
2021,SEVILLA,6102.0,6091.0,1746.0,499.0
2021,SORIA,166.0,166.0,94.0,11.0
2021,TARRAGONA,2756.0,2756.0,802.0,269.0
2021,TERUEL,196.0,196.0,53.0,7.0
2021,TOLEDO,2094.0,1976.0,488.0,400.0
2021,VALENCIA,6139.0,6109.0,1269.0,1289.0
2021,VALENCIA/VALÈNCIA,5219.0,4975.0,1142.0,878.0
2021,VALLADOLID,1339.0,1335.0,433.0,70.0
2021,ZAMORA,282.0,282.0,93.0,36.0
2021,ZARAGOZA,3339.0,2900.0,647.0,377.0
2022,A CORUNA,2898.0,2817.0,866.0,444.0
2022,ALBACETE,999.0,999.0,347.0,137.0
2022,ALICANTE,5153.0,5153.0,1435.0,777.0
2022,ALICANTE/ALACANT,4627.0,4578.0,794.0,495.0
2022,ALMERIA,4060.0,4031.0,1101.0,457.0
2022,ARABA/ALAVA,1079.0,1079.0,125.0,65.0
2022,ASTURIAS,3002.0,2811.0,858.0,453.0
2022,AVILA,437.0,437.0,111.0,48.0
2022,BADAJOZ,2002.0,1984.0,603.0,193.0
2022,BARCELONA,15605.0,15322.0,3769.0,1781.0
2022,BIZKAIA,3450.0,3450.0,636.0,184.0
2022,BURGOS,958.0,957.0,291.0,75.0
2022,CACERES,1154.0,1153.0,352.0,229.0
2022,CADIZ,5527.0,5149.0,1209.0,1284.0
2022,CANTABRIA,2218.0,2087.0,422.0,231.0
2022,CASTELLON,3899.0,2438.0,465.0,1798.0
2022,CASTELLON/CASTELLO,0.0,0.0,0.0,0.0
2022,CIUDAD AUTONOMA DE CEUTA,250.0,250.0,92.0,5.0
2022,CIUDAD AUTONOMA DE MELILLA,358.0,358.0,84.0,23.0
2022,CIUDAD REAL,1633.0,1633.0,451.0,228.0
2022,CORDOBA,2840.0,2840.0,418.0,203.0
2022,CUENCA,516.0,516.0,183.0,37.0
2022,GIPUZKOA,1566.0,1543.0,281.0,198.0
2022,GIRONA,3701.0,3701.0,749.0,375.0
2022,GRANADA,5325.0,4986.0,1183.0,673.0
2022,GUADALAJARA,910.0,908.0,160.0,315.0
2022,HUELVA,2572.0,2570.0,539.0,87.0
2022,HUESCA,499.0,497.0,177.0,57.0
2022,ILLES BALEARS,7000.0,6516.0,1400.0,621.0
2022,JAEN,2238.0,2230.0,562.0,207.0
2022,LA RIOJA,893.0,869.0,326.0,41.0
2022,LAS PALMAS,5483.0,5457.0,926.0,339.0
2022,LEON,1061.0,1061.0,241.0,178.0
2022,LLEIDA,1755.0,1755.0,392.0,110.0
2022,LUGO,730.0,728.0,212.0,125.0
2022,MADRID,25912.0,24833.0,5319.0,3420.0
2022,MALAGA,8276.0,8235.0,1412.0,1099.0
2022,MURCIA,7904.0,7904.0,1569.0,832.0
2022,NAVARRA,2352.0,2352.0,426.0,336.0
2022,OURENSE,1035.0,1035.0,264.0,290.0
2022,PALENCIA,349.0,349.0,125.0,120.0
2022,PONTEVEDRA,2332.0,2332.0,612.0,182.0
2022,SALAMANCA,523.0,523.0,138.0,37.0
2022,SANTA CRUZ DE TENERIFE,4274.0,4264.0,938.0,340.0
2022,SEGOVIA,568.0,568.0,103.0,87.0
2022,SEVILLA,7307.0,7295.0,1890.0,794.0
2022,SORIA,210.0,210.0,104.0,7.0
2022,TARRAGONA,2948.0,2948.0,736.0,267.0
2022,TERUEL,271.0,271.0,69.0,25.0
2022,TOLEDO,2275.0,2095.0,582.0,402.0
2022,VALENCIA,6246.0,6179.0,1366.0,1159.0
2022,VALENCIA/VALÈNCIA,5785.0,5533.0,1315.0,896.0
2022,VALLADOLID,1295.0,1273.0,464.0,195.0
2022,ZAMORA,264.0,264.0,110.0,19.0
2022,ZARAGOZA,3684.0,3300.0,721.0,448.0
2023,A CORUNA,3155.0,3155.0,873.0,270.0
2023,ALBACETE,1116.0,1116.0,376.0,184.0
2023,ALICANTE,5820.0,5787.0,1626.0,991.0
2023,ALICANTE/ALACANT,5102.0,5098.0,840.0,378.0
2023,ALMERIA,4271.0,4071.0,1044.0,455.0
2023,ARABA/ALAVA,1187.0,1187.0,119.0,128.0

In [0]:
display(
    dataset_judicial_provincia
    .select("anio")
    .distinct()
    .orderBy("anio")
)

anio
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024

In [0]:
dataset_judicial_provincia.write.mode("overwrite").format("delta").save(
    "/Volumes/workspace/default/tfm_visnu_raw/dataset_judicial_provincia_delta"
)